import { Server, Socket } from 'socket.io';
import { nanoid } from 'nanoid';
import { db } from '../db';
import { broadcastArcadeKiosk } from '../realtime';
import { startArcadeSession, endArcadeSession } from './arcadeTracking';
import { recordArcadeResult } from './arcadeData';
import { canJoinLobby, canUseLobby, emitArcadeRoom, socketArcadeScope } from './scope';
import { claimLobbyMembership, releaseLobbyMembership, releaseLobbyMemberships } from './lobbyMembership';
import { isLobbyReady, setLobbyReady } from './lobbyReady';
import { arcadeTiming } from './timing';
import { CHALLENGES, challengePayload, scoreCps, scoreNumberSalad, scoreReaction, scoreTiming10, type ChallengeKey } from './challengeRushLogic';

interface Player { id: string; name: string; avatar: string | null; color: string | null }
interface Lobby { id: string; groupId: string; eventId: string | null; host: Player; players: Player[]; socketIds: Map<string, string>; ready: Set<string>; createdAt: number }
interface Progress { clicks: number; errors: number; correct: number; completed: boolean; score: number; startedAt: number; lastInputAt: number }
interface Match { id: string; groupId: string; eventId: string | null; room: string; host: Player; players: Player[]; socketIds: Map<string, string>; order: ChallengeKey[]; index: number; phase: 'countdown' | 'playing' | 'result' | 'ended'; seed: number; current: ReturnType<typeof challengePayload>; progress: Map<string, Progress>; scores: Map<string, number>; startedAt: number; timer: NodeJS.Timeout | null; paused: boolean }

const lobbies = new Map<string, Lobby>(); const matches = new Map<string, Match>();
const real = (players: Player[]) => players.filter((player) => !player.id.startsWith('bot-')).map((player) => player.id);
const playerById = (id: unknown): Player | null => typeof id === 'string' ? (db.prepare('SELECT id,name,avatar,color FROM players WHERE id=?').get(id) as Player | undefined) ?? null : null;
const owns = (socket: Socket, id: unknown): id is string => typeof id === 'string' && Boolean(socketArcadeScope(socket, id));
const publicLobbies = (groupId: string, eventId: string | null) => [...lobbies.values()].filter((l) => l.groupId === groupId && l.eventId === eventId).map((l) => ({ id: l.id, host: l.host, players: l.players.map((p) => ({ ...p, ready: isLobbyReady(l, p.id) })), createdAt: l.createdAt }));
function emitLobbies(io: Server) { for (const socket of io.sockets.sockets.values()) { const scope = socketArcadeScope(socket); if (scope) socket.emit('challenge-rush:lobbies', { lobbies: publicLobbies(scope.groupId, scope.eventId) }); } }
function scorePayload(match: Match) { return match.players.map((p) => ({ playerId: p.id, name: p.name, score: match.scores.get(p.id) ?? 0 })); }
function emitState(io: Server, match: Match) { const state = { matchId: match.id, phase: match.phase, challengeIndex: match.index, challengeCount: match.order.length, challenge: match.current, scores: scorePayload(match), paused: match.paused }; emitArcadeRoom(io, match.room, 'challenge-rush:state', state, match); broadcastArcadeKiosk(io, { gameType: 'challenge-rush', matchId: match.id, groupId: match.groupId, eventId: match.eventId, phase: match.phase, challenge: match.current.title, scores: state.scores, paused: match.paused }); }
function finishChallenge(io: Server, match: Match) {
  if (match.phase !== 'playing') return;
  match.phase = 'result'; if (match.timer) clearTimeout(match.timer);
  for (const player of match.players) { const p = match.progress.get(player.id)!; if (!p.completed) { const elapsed = Math.min(Date.now() - p.startedAt, match.current.durationMs); p.score = match.current.key === 'cps' ? scoreCps(p.clicks) : match.current.key === 'number-salad' ? scoreNumberSalad(p.correct, p.errors, elapsed) : match.current.key === 'timing-10' ? scoreTiming10(elapsed) : 0; p.completed = true; } match.scores.set(player.id, (match.scores.get(player.id) ?? 0) + p.score); }
  emitState(io, match); emitArcadeRoom(io, match.room, 'challenge-rush:challenge:end', { matchId: match.id, scores: scorePayload(match) }, match);
  match.timer = setTimeout(() => nextChallenge(io, match), 1_500);
}
function nextChallenge(io: Server, match: Match) { if (matches.get(match.id) !== match) return; if (match.index + 1 >= match.order.length) return finishMatch(io, match); match.index += 1; match.phase = 'countdown'; match.current = challengePayload(match.order[match.index], (match.seed + match.index * 7919) >>> 0); match.progress = new Map(match.players.map((p) => [p.id, { clicks: 0, errors: 0, correct: 0, completed: false, score: 0, startedAt: 0, lastInputAt: 0 }])); emitState(io, match); match.timer = setTimeout(() => { if (match.phase !== 'countdown') return; match.phase = 'playing'; const now = Date.now(); for (const p of match.progress.values()) p.startedAt = now; emitState(io, match); match.timer = setTimeout(() => finishChallenge(io, match), match.current.durationMs); }, arcadeTiming.countdownMs); }
function finishMatch(io: Server, match: Match) { if (match.phase === 'ended') return; match.phase = 'ended'; if (match.timer) clearTimeout(match.timer); const scores = scorePayload(match); const winner = [...scores].sort((a, b) => b.score - a.score)[0]?.playerId ?? null; endArcadeSession(real(match.players), 'challenge-rush', match); recordArcadeResult({ gameType: 'challenge-rush', winnerId: winner, players: match.players, scores, reason: 'completed', startedAt: match.startedAt, scope: match }); emitArcadeRoom(io, match.room, 'challenge-rush:match:end', { matchId: match.id, winnerId: winner, scores }, match); broadcastArcadeKiosk(io, { gameType: 'challenge-rush', matchId: match.id, groupId: match.groupId, eventId: match.eventId, phase: 'ended', scores }); releaseLobbyMemberships([], 'challenge-rush', match.id); matches.delete(match.id); }
function startMatch(io: Server, lobby: Lobby) { const id = nanoid(); const room = `challenge-rush:${id}`; for (const socketId of lobby.socketIds.values()) io.sockets.sockets.get(socketId)?.join(room); const seed = Math.floor(Math.random() * 0x7fffffff); const order = CHALLENGES.map((c) => c.key); const match: Match = { id, groupId: lobby.groupId, eventId: lobby.eventId, room, host: lobby.host, players: [...lobby.players], socketIds: new Map(lobby.socketIds), order, index: -1, phase: 'countdown', seed, current: challengePayload(order[0], seed), progress: new Map(), scores: new Map(lobby.players.map((p) => [p.id, 0])), startedAt: Date.now(), timer: null, paused: false }; matches.set(id, match); releaseLobbyMemberships(lobby.players.map((p) => p.id), 'challenge-rush', lobby.id); lobbies.delete(lobby.id); emitLobbies(io); startArcadeSession(real(match.players), 'challenge-rush', match); emitArcadeRoom(io, room, 'challenge-rush:match:start', { matchId: id, players: match.players, challengeCount: order.length }, match); nextChallenge(io, match); return match; }

export function registerChallengeRushSockets(io: Server): void { io.on('connection', (socket: Socket) => {
  const sendLobbies = () => { const scope = socketArcadeScope(socket); if (scope) socket.emit('challenge-rush:lobbies', { lobbies: publicLobbies(scope.groupId, scope.eventId) }); }; sendLobbies(); socket.on('challenge-rush:lobbies:get', sendLobbies); socket.on('scope:subscribe', sendLobbies); socket.on('room:subscribe', sendLobbies);
  socket.on('challenge-rush:lobby:create', (payload: { playerId?: string }, ack?: (r: unknown) => void) => { const player = playerById(payload?.playerId); const scope = player ? socketArcadeScope(socket, player.id) : null; if (!player || !scope) return ack?.({ ok: false, error: 'Spieler- oder Gruppenzugriff verweigert.' }); const lobby: Lobby = { id: nanoid(), ...scope, host: player, players: [player], socketIds: new Map([[player.id, socket.id]]), ready: new Set(), createdAt: Date.now() }; if (!claimLobbyMembership(player.id, 'challenge-rush', lobby.id)) return ack?.({ ok: false, error: 'Du bist bereits in einer Arcade-Lobby.' }); lobbies.set(lobby.id, lobby); emitLobbies(io); ack?.({ ok: true, lobbyId: lobby.id }); });
  socket.on('challenge-rush:lobby:join', (payload: { lobbyId?: string; playerId?: string }, ack?: (r: unknown) => void) => { const lobby = payload?.lobbyId ? lobbies.get(payload.lobbyId) : null; const player = playerById(payload?.playerId); if (!lobby || !player || !canJoinLobby(socket, lobby, player.id)) return ack?.({ ok: false, error: 'Lobbyzugriff verweigert.' }); if (!lobby.players.some((p) => p.id === player.id) && lobby.players.length >= 15) return ack?.({ ok: false, error: 'Lobby ist voll.' }); if (!claimLobbyMembership(player.id, 'challenge-rush', lobby.id)) return ack?.({ ok: false, error: 'Du bist bereits in einer Arcade-Lobby.' }); if (!lobby.players.some((p) => p.id === player.id)) lobby.players.push(player); lobby.socketIds.set(player.id, socket.id); emitLobbies(io); ack?.({ ok: true }); });
  socket.on('challenge-rush:lobby:leave', (payload: { lobbyId?: string; playerId?: string }, ack?: (r: unknown) => void) => { const lobby = payload?.lobbyId ? lobbies.get(payload.lobbyId) : null; if (!lobby || !canUseLobby(socket, lobby) || !owns(socket, payload.playerId)) return ack?.({ ok: false, error: 'Lobbyzugriff verweigert.' }); releaseLobbyMembership(payload.playerId, 'challenge-rush', lobby.id); if (payload.playerId === lobby.host.id) { releaseLobbyMemberships(lobby.players.map((p) => p.id), 'challenge-rush', lobby.id); lobbies.delete(lobby.id); } else { lobby.players = lobby.players.filter((p) => p.id !== payload.playerId); lobby.socketIds.delete(payload.playerId); lobby.ready.delete(payload.playerId); } emitLobbies(io); ack?.({ ok: true }); });
  socket.on('challenge-rush:lobby:ready', (payload: { lobbyId?: string; playerId?: string; ready?: boolean }, ack?: (r: unknown) => void) => { const lobby = payload?.lobbyId ? lobbies.get(payload.lobbyId) : null; if (!lobby || !canUseLobby(socket, lobby) || !owns(socket, payload.playerId) || !setLobbyReady(lobby, payload.playerId, payload.ready)) return ack?.({ ok: false, error: 'Bereit-Status konnte nicht gesetzt werden.' }); emitLobbies(io); ack?.({ ok: true }); });
  socket.on('challenge-rush:lobby:start', (payload: { lobbyId?: string; playerId?: string }, ack?: (r: unknown) => void) => { const lobby = payload?.lobbyId ? lobbies.get(payload.lobbyId) : null; if (!lobby || !canUseLobby(socket, lobby) || !owns(socket, payload.playerId) || payload.playerId !== lobby.host.id) return ack?.({ ok: false, error: 'Nur der Host kann starten.' }); if (lobby.players.length < 1 || lobby.players.some((p) => !isLobbyReady(lobby, p.id))) return ack?.({ ok: false, error: 'Alle Mitspieler müssen bereit sein.' }); const match = startMatch(io, lobby); ack?.({ ok: true, matchId: match.id }); });
  socket.on('challenge-rush:challenge:input', (payload: { matchId?: string; playerId?: string; action?: string; value?: number | { x?: number; y?: number } }, ack?: (r: unknown) => void) => { const match = payload?.matchId ? matches.get(payload.matchId) : null; const p = match && payload.playerId ? match.progress.get(payload.playerId) : null; if (!match || match.phase !== 'playing' || match.paused || !p || !owns(socket, payload.playerId) || !canUseLobby(socket, match)) return ack?.({ ok: false, error: 'Eingabe nicht möglich.' }); const now = Date.now(); if (p.completed) return ack?.({ ok: true, duplicate: true }); if (now - p.lastInputAt < 30) return ack?.({ ok: true, ignored: true }); p.lastInputAt = now; const elapsed = now - p.startedAt; if (match.current.key === 'reaction-circle') { const point = payload.value && typeof payload.value === 'object' ? payload.value : {}; const target = match.current.data; const validPoint = typeof point.x === 'number' && typeof point.y === 'number' && Math.abs(point.x - Number(target.x)) <= 12 && Math.abs(point.y - Number(target.y)) <= 12; if (payload.action !== 'hit' || !validPoint) return ack?.({ ok: false, error: 'Ungültiges Ziel.' }); p.score = scoreReaction(elapsed); p.completed = true; } else if (match.current.key === 'cps') { if (payload.action === 'click') p.clicks += 1; } else if (match.current.key === 'number-salad') { const expected = p.correct + 1; if (payload.action !== 'number' || payload.value !== expected) p.errors += 1; else p.correct += 1; if (p.correct >= 8) { p.score = scoreNumberSalad(p.correct, p.errors, elapsed); p.completed = true; } } else if (match.current.key === 'timing-10') { if (payload.action !== 'stop') return ack?.({ ok: false, error: 'Ungültige Eingabe.' }); p.score = scoreTiming10(elapsed); p.completed = true; } if ([...match.progress.values()].every((entry) => entry.completed)) finishChallenge(io, match); ack?.({ ok: true, score: p.score }); });
  socket.on('challenge-rush:match:pause', (payload: { matchId?: string; playerId?: string }, ack?: (r: unknown) => void) => { const match = payload?.matchId ? matches.get(payload.matchId) : null; if (!match || payload.playerId !== match.host.id || !owns(socket, payload.playerId) || !canUseLobby(socket, match)) return ack?.({ ok: false, error: 'Nur der Host kann pausieren.' }); match.paused = !match.paused; emitState(io, match); ack?.({ ok: true }); });
  socket.on('disconnect', () => { for (const [id, lobby] of lobbies) { if ([...lobby.socketIds.values()].includes(socket.id)) { releaseLobbyMemberships(lobby.players.map((p) => p.id), 'challenge-rush', id); lobbies.delete(id); } } emitLobbies(io); });
 }); }
