export interface QuizQuestionSeed {
  question: string;
  answers: string[];
  category: string;
  difficulty: string;
}

export const DEFAULT_QUIZ_QUESTIONS: QuizQuestionSeed[] = [
  { question: 'Wie hieß Super Mario ursprünglich?', answers: ['Jumpman'], category: 'Klassiker', difficulty: 'mittel' },
  { question: 'In welchem Spiel sammelt man Triforce-Fragmente?', answers: ['The Legend of Zelda', 'Zelda'], category: 'Nintendo', difficulty: 'leicht' },
  { question: 'Welches Studio entwickelte Half-Life?', answers: ['Valve'], category: 'PC', difficulty: 'leicht' },
  { question: 'Wie heißt die Stadt aus GTA: Vice City?', answers: ['Vice City'], category: 'Open World', difficulty: 'leicht' },
  { question: 'Welche Firma steckt hinter der PlayStation?', answers: ['Sony'], category: 'Hardware', difficulty: 'leicht' },
  { question: 'Wie heißt der blaue Igel von Sega?', answers: ['Sonic', 'Sonic the Hedgehog'], category: 'Klassiker', difficulty: 'leicht' },
  { question: 'Welche Farbe hat der erste Tetris-Stein I in vielen modernen Versionen?', answers: ['Cyan', 'Hellblau', 'Blau'], category: 'Klassiker', difficulty: 'mittel' },
  { question: 'Wie heißt der Hauptcharakter in Halo?', answers: ['Master Chief', 'John 117'], category: 'Shooter', difficulty: 'leicht' },
  { question: 'Welche Engine nutzt Fortnite?', answers: ['Unreal Engine', 'Unreal'], category: 'Technik', difficulty: 'leicht' },
  { question: 'Wie heißt die Spielwelt von The Elder Scrolls V?', answers: ['Skyrim'], category: 'RPG', difficulty: 'leicht' },
  { question: 'Welche Ressource baut man in StarCraft mit Arbeitern ab?', answers: ['Mineralien', 'Minerals'], category: 'RTS', difficulty: 'leicht' },
  { question: 'Wie heißt der Terroristen-Bombenplatz im Counter-Strike-Jargon?', answers: ['Bombsite', 'Spot', 'Bombenplatz'], category: 'Shooter', difficulty: 'leicht' },
  { question: 'Welches Spiel machte den Satz "The cake is a lie" bekannt?', answers: ['Portal'], category: 'PC', difficulty: 'leicht' },
  { question: 'Wie heißt der Companion Cube vollständig?', answers: ['Weighted Companion Cube', 'Companion Cube'], category: 'PC', difficulty: 'mittel' },
  { question: 'In welchem Spiel taucht der Charakter GLaDOS auf?', answers: ['Portal'], category: 'PC', difficulty: 'leicht' },
  { question: 'Welche Firma entwickelte Warcraft III?', answers: ['Blizzard', 'Blizzard Entertainment'], category: 'RTS', difficulty: 'leicht' },
  { question: 'Wie heißt die MOBA-Karte in League of Legends?', answers: ['Summoners Rift', "Summoner's Rift", 'Kluft der Beschwörer'], category: 'MOBA', difficulty: 'leicht' },
  { question: 'Wie heißt der Fußballmodus mit Autos von Psyonix?', answers: ['Rocket League'], category: 'Multiplayer', difficulty: 'leicht' },
  { question: 'Wie viele Spieler hat ein Standard-Team in Rocket League 3v3?', answers: ['3', 'drei'], category: 'Multiplayer', difficulty: 'leicht' },
  { question: 'Welche Waffe ist in CS besonders mit One-Tap-Headshots verbunden?', answers: ['AK-47', 'AK47', 'AK'], category: 'Shooter', difficulty: 'leicht' },
  { question: 'Welche Karte aus CS spielt in Italien?', answers: ['Inferno'], category: 'Shooter', difficulty: 'mittel' },
  { question: 'Wie heißt der Rang über Legendary Eagle Master in CS:GO?', answers: ['Supreme Master First Class', 'Supreme'], category: 'Shooter', difficulty: 'schwer' },
  { question: 'Wie heißt die Allianz-Fraktion in Warcraft?', answers: ['Allianz', 'Alliance'], category: 'RTS', difficulty: 'leicht' },
  { question: 'Welche Einheit ruft in Age of Empires "Wololo"?', answers: ['Mönch', 'Monk', 'Priester'], category: 'RTS', difficulty: 'leicht' },
  { question: 'Welche Ressource ist in Age of Empires 2 neben Holz, Nahrung und Gold wichtig?', answers: ['Stein', 'Stone'], category: 'RTS', difficulty: 'leicht' },
  { question: 'Wie heißt der Steam-Betreiber?', answers: ['Valve'], category: 'PC', difficulty: 'leicht' },
  { question: 'Welches Spiel startete als Warcraft-III-Mod?', answers: ['Dota', 'Defense of the Ancients'], category: 'MOBA', difficulty: 'mittel' },
  { question: 'Wie heißt der Standard-Ball in Rocket League?', answers: ['Ball'], category: 'Multiplayer', difficulty: 'leicht' },
  { question: 'Welche Serie enthält den Modus "Zombies" besonders bekannt?', answers: ['Call of Duty', 'COD'], category: 'Shooter', difficulty: 'leicht' },
  { question: 'Wie heißt der Koop-Zombie-Shooter von Valve?', answers: ['Left 4 Dead', 'Left 4 Dead 2'], category: 'Shooter', difficulty: 'leicht' },
  { question: 'Wie heißt der Pilz-Königreich-Held mit roter Mütze?', answers: ['Mario', 'Super Mario'], category: 'Nintendo', difficulty: 'leicht' },
  { question: 'Wie heißt Marios Bruder?', answers: ['Luigi'], category: 'Nintendo', difficulty: 'leicht' },
  { question: 'Wie heißt die Prinzessin, die Mario oft rettet?', answers: ['Peach', 'Princess Peach'], category: 'Nintendo', difficulty: 'leicht' },
  { question: 'Wie heißt Links Pferd?', answers: ['Epona'], category: 'Nintendo', difficulty: 'mittel' },
  { question: 'Welche Kreatur sagt in Minecraft "Ssss" bevor sie explodiert?', answers: ['Creeper'], category: 'Sandbox', difficulty: 'leicht' },
  { question: 'Welche Dimension erreicht man in Minecraft über Obsidian?', answers: ['Nether', 'Der Nether'], category: 'Sandbox', difficulty: 'leicht' },
  { question: 'Wie heißt der Endboss in Minecraft?', answers: ['Enderdrache', 'Ender Dragon'], category: 'Sandbox', difficulty: 'leicht' },
  { question: 'Welche Währung nutzt man in The Witcher 3 hauptsächlich?', answers: ['Kronen', 'Crowns'], category: 'RPG', difficulty: 'mittel' },
  { question: 'Wie heißt der Hexer aus The Witcher?', answers: ['Geralt', 'Geralt von Riva', 'Geralt of Rivia'], category: 'RPG', difficulty: 'leicht' },
  { question: 'Wie heißt Geralts Pferd?', answers: ['Plötze', 'Roach'], category: 'RPG', difficulty: 'mittel' },
  { question: 'Welche Firma veröffentlichte Cyberpunk 2077?', answers: ['CD Projekt', 'CD Projekt Red', 'CDPR'], category: 'RPG', difficulty: 'leicht' },
  { question: 'Wie heißt die Stadt in Cyberpunk 2077?', answers: ['Night City'], category: 'RPG', difficulty: 'leicht' },
  { question: 'Welche Figur spielt Keanu Reeves in Cyberpunk 2077?', answers: ['Johnny Silverhand'], category: 'RPG', difficulty: 'mittel' },
  { question: 'Wie heißt das Battle-Royale-Spiel von Respawn im Titanfall-Universum?', answers: ['Apex Legends'], category: 'Shooter', difficulty: 'leicht' },
  { question: 'Welche Firma entwickelte Titanfall?', answers: ['Respawn', 'Respawn Entertainment'], category: 'Shooter', difficulty: 'mittel' },
  { question: 'Wie heißt der Modus, bei dem am Ende nur ein Team übrig bleibt?', answers: ['Battle Royale'], category: 'Genres', difficulty: 'leicht' },
  { question: 'Welche Taste ist auf PC oft Standard für Nachladen?', answers: ['R'], category: 'PC', difficulty: 'leicht' },
  { question: 'Welche Taste ist auf PC oft Standard für Springen?', answers: ['Leertaste', 'Space', 'Spacebar'], category: 'PC', difficulty: 'leicht' },
  { question: 'Was bedeutet FPS als Genre-Abkürzung?', answers: ['First Person Shooter', 'Ego-Shooter'], category: 'Genres', difficulty: 'leicht' },
  { question: 'Was bedeutet RTS?', answers: ['Real Time Strategy', 'Echtzeitstrategie'], category: 'Genres', difficulty: 'mittel' },
  { question: 'Was bedeutet RPG?', answers: ['Role Playing Game', 'Rollenspiel'], category: 'Genres', difficulty: 'leicht' },
  { question: 'Was bedeutet MMO?', answers: ['Massively Multiplayer Online'], category: 'Genres', difficulty: 'mittel' },
  { question: 'Welche Konsole folgte auf den GameCube?', answers: ['Wii', 'Nintendo Wii'], category: 'Hardware', difficulty: 'leicht' },
  { question: 'Welche Microsoft-Konsole erschien zuerst?', answers: ['Xbox', 'Original Xbox'], category: 'Hardware', difficulty: 'leicht' },
  { question: 'Wie heißt Nintendos Handheld mit zwei Bildschirmen?', answers: ['Nintendo DS', 'DS'], category: 'Hardware', difficulty: 'leicht' },
  { question: 'Wie heißt Valves Handheld-PC?', answers: ['Steam Deck'], category: 'Hardware', difficulty: 'leicht' },
  { question: 'Welches Studio entwickelte Elden Ring?', answers: ['FromSoftware', 'From Software'], category: 'RPG', difficulty: 'leicht' },
  { question: 'Wer schrieb an der Welt von Elden Ring mit?', answers: ['George R. R. Martin', 'George Martin'], category: 'RPG', difficulty: 'mittel' },
  { question: 'Wie heißt die Dark-Souls-Währung/Erfahrung?', answers: ['Seelen', 'Souls'], category: 'RPG', difficulty: 'leicht' },
  { question: 'Wie heißt das Lagerfeuer-System in Dark Souls?', answers: ['Bonfire', 'Leuchtfeuer'], category: 'RPG', difficulty: 'mittel' },
  { question: 'Wie heißt die ikonische Pistole aus Halo?', answers: ['Magnum', 'M6D'], category: 'Shooter', difficulty: 'mittel' },
  { question: 'Wie heißt die KI-Begleiterin des Master Chief?', answers: ['Cortana'], category: 'Shooter', difficulty: 'leicht' },
  { question: 'Welche Serie nutzt den Ring als Megastruktur?', answers: ['Halo'], category: 'Shooter', difficulty: 'leicht' },
  { question: 'Wie heißt der Hauptplanet aus Mass Effect 1 am Anfang nicht, sondern die Citadel-Station?', answers: ['Citadel', 'Die Citadel'], category: 'RPG', difficulty: 'mittel' },
  { question: 'Wie heißt Commander Shepards Schiff?', answers: ['Normandy', 'SSV Normandy'], category: 'RPG', difficulty: 'mittel' },
  { question: 'Welche Firma entwickelte Mass Effect?', answers: ['BioWare', 'Bioware'], category: 'RPG', difficulty: 'leicht' },
  { question: 'Wie heißt das Strategiespiel mit Zerg, Terranern und Protoss?', answers: ['StarCraft', 'StarCraft 2'], category: 'RTS', difficulty: 'leicht' },
  { question: 'Welche StarCraft-Fraktion ist insektenartig?', answers: ['Zerg'], category: 'RTS', difficulty: 'leicht' },
  { question: 'Welche StarCraft-Fraktion sind Menschen?', answers: ['Terraner', 'Terran'], category: 'RTS', difficulty: 'leicht' },
  { question: 'Welche StarCraft-Fraktion nutzt Pylonen?', answers: ['Protoss'], category: 'RTS', difficulty: 'leicht' },
  { question: 'Wie heißt das Blizzard-Kartenspiel?', answers: ['Hearthstone'], category: 'Blizzard', difficulty: 'leicht' },
  { question: 'Wie heißt Blizzards Helden-Shooter?', answers: ['Overwatch'], category: 'Shooter', difficulty: 'leicht' },
  { question: 'Wie heißt der Panda-Kontinent in World of Warcraft?', answers: ['Pandaria'], category: 'MMO', difficulty: 'mittel' },
  { question: 'Wie heißt die Horde-Hauptstadt der Orcs?', answers: ['Orgrimmar'], category: 'MMO', difficulty: 'mittel' },
  { question: 'Wie heißt die Allianz-Hauptstadt der Menschen?', answers: ['Sturmwind', 'Stormwind'], category: 'MMO', difficulty: 'mittel' },
  { question: 'Welche Valve-Serie hat Gordon Freeman als Hauptfigur?', answers: ['Half-Life', 'Half Life'], category: 'PC', difficulty: 'leicht' },
  { question: 'Welche Waffe ist Gordon Freemans Markenzeichen?', answers: ['Brecheisen', 'Crowbar'], category: 'PC', difficulty: 'leicht' },
  { question: 'Wie heißt die Alien-Dimension in Half-Life?', answers: ['Xen'], category: 'PC', difficulty: 'mittel' },
  { question: 'Wie heißt das Kartenspiel in The Witcher 3?', answers: ['Gwent', 'Gwint'], category: 'RPG', difficulty: 'leicht' },
  { question: 'Wie heißt der Fußballmanager von Sports Interactive?', answers: ['Football Manager'], category: 'Simulation', difficulty: 'leicht' },
  { question: 'Welche Reihe simuliert Städtebau von Colossal Order?', answers: ['Cities Skylines', 'Cities: Skylines'], category: 'Simulation', difficulty: 'leicht' },
  { question: 'Welche Serie nutzt "Plumbobs" über den Figuren?', answers: ['Die Sims', 'The Sims'], category: 'Simulation', difficulty: 'leicht' },
  { question: 'Wie heißt die Bauernhof-Serie von ConcernedApe?', answers: ['Stardew Valley'], category: 'Indie', difficulty: 'leicht' },
  { question: 'Wie heißt der Entwickler von Stardew Valley?', answers: ['ConcernedApe', 'Eric Barone'], category: 'Indie', difficulty: 'mittel' },
  { question: 'Welches Indie-Spiel spielt im Untergrund mit Monstern und Mercy-System?', answers: ['Undertale'], category: 'Indie', difficulty: 'leicht' },
  { question: 'Wie heißt der Skelett-Charakter aus Undertale?', answers: ['Sans'], category: 'Indie', difficulty: 'leicht' },
  { question: 'Welches Spiel hat den Satz "Praise the sun" geprägt?', answers: ['Dark Souls'], category: 'RPG', difficulty: 'leicht' },
  { question: 'Wie heißt der Battle-Bus in Fortnite auf Deutsch meist?', answers: ['Battle Bus', 'Kampfbus'], category: 'Battle Royale', difficulty: 'leicht' },
  { question: 'Welche Ressource baut man in Fortnite zum Bauen ab?', answers: ['Materialien', 'Holz', 'Stein', 'Metall'], category: 'Battle Royale', difficulty: 'leicht' },
  { question: 'Wie heißt die Inselkarte in PUBG ursprünglich?', answers: ['Erangel'], category: 'Battle Royale', difficulty: 'mittel' },
  { question: 'Wofür steht PUBG?', answers: ['PlayerUnknowns Battlegrounds', "PlayerUnknown's Battlegrounds"], category: 'Battle Royale', difficulty: 'mittel' },
  { question: 'Wie heißt das Social-Deduction-Spiel mit Crewmates?', answers: ['Among Us'], category: 'Multiplayer', difficulty: 'leicht' },
  { question: 'Wie nennt man den Verräter in Among Us?', answers: ['Impostor', 'Imposter'], category: 'Multiplayer', difficulty: 'leicht' },
  { question: 'Welche Farbe ist bei Among Us oft sus im Meme?', answers: ['Rot', 'Red'], category: 'Memes', difficulty: 'leicht' },
  { question: 'Wie heißt das Koop-Kochspiel mit chaotischen Küchen?', answers: ['Overcooked', 'Overcooked 2'], category: 'Party', difficulty: 'leicht' },
  { question: 'Welches Partyspiel nutzt Kronen und Hindernis-Parcours?', answers: ['Fall Guys'], category: 'Party', difficulty: 'leicht' },
  { question: 'Welches Spiel ist Minigolf mit verrückten Bahnen?', answers: ['Golf with your Friends'], category: 'Party', difficulty: 'leicht' },
  { question: 'Wie heißt das Spiel mit klebrigen Tieren und Fallen?', answers: ['Ultimate Chicken Horse'], category: 'Party', difficulty: 'mittel' },
  { question: 'Welches Spiel stapelt Türme mit Zauberern?', answers: ['Tricky Towers'], category: 'Party', difficulty: 'mittel' },
  { question: 'Welche Reihe ist für "Fatality" bekannt?', answers: ['Mortal Kombat'], category: 'Fighting', difficulty: 'leicht' },
  { question: 'Welche Reihe hat Ryu und Ken?', answers: ['Street Fighter'], category: 'Fighting', difficulty: 'leicht' },
  { question: 'Wie heißt Nintendos Plattform-Prügler?', answers: ['Super Smash Bros', 'Smash Bros'], category: 'Fighting', difficulty: 'leicht' },
  { question: 'Welche Figur ruft "Hadouken"?', answers: ['Ryu', 'Ken'], category: 'Fighting', difficulty: 'mittel' },
  { question: 'Wie heißt die Rennspiel-Serie mit Item-Kisten von Nintendo?', answers: ['Mario Kart'], category: 'Racing', difficulty: 'leicht' },
  { question: 'Welche Item-Schale verfolgt in Mario Kart den Führenden?', answers: ['Blauer Panzer', 'Blue Shell', 'Stachi-Panzer'], category: 'Racing', difficulty: 'leicht' },
  { question: 'Wie heißt Ubisofts Zeitfahr-Rennserie mit wilden Strecken?', answers: ['Trackmania'], category: 'Racing', difficulty: 'leicht' },
  { question: 'Welches Rennspiel ist für Schrott und Demolition bekannt?', answers: ['Wreckfest'], category: 'Racing', difficulty: 'leicht' },
  { question: 'Wie heißt die Unreal-Tournament-Waffe mit zwei Feuermodi und Kugel/Splitter?', answers: ['Flak Cannon', 'Flak'], category: 'Shooter', difficulty: 'mittel' },
  { question: 'Wie heißt der UT-Modus mit Flaggenklau?', answers: ['Capture the Flag', 'CTF'], category: 'Shooter', difficulty: 'leicht' },
  { question: 'Welche Shooter-Reihe hat die Map Nuketown?', answers: ['Call of Duty', 'COD'], category: 'Shooter', difficulty: 'leicht' },
  { question: 'Welche Battlefield-Klasse repariert Fahrzeuge häufig?', answers: ['Engineer', 'Pionier'], category: 'Shooter', difficulty: 'mittel' },
  { question: 'Wie heißt das Riot-Taktik-Shooter-Spiel?', answers: ['Valorant'], category: 'Shooter', difficulty: 'leicht' },
  { question: 'Welche Waffe in Valorant entspricht grob einer AWP?', answers: ['Operator', 'Op'], category: 'Shooter', difficulty: 'mittel' },
  { question: 'Wie heißt die AWP in Counter-Strike ausgeschrieben?', answers: ['Arctic Warfare Police', 'AWP'], category: 'Shooter', difficulty: 'schwer' },
  { question: 'Welche Rolle schützt in MMOs typischerweise die Gruppe vor Schaden?', answers: ['Tank'], category: 'Genres', difficulty: 'leicht' },
  { question: 'Welche Rolle heilt in MMOs?', answers: ['Heiler', 'Healer', 'Support'], category: 'Genres', difficulty: 'leicht' },
  { question: 'Was bedeutet GG am Ende eines Spiels?', answers: ['Good Game', 'Gutes Spiel'], category: 'Memes', difficulty: 'leicht' },
  { question: 'Was bedeutet AFK?', answers: ['Away From Keyboard'], category: 'Memes', difficulty: 'leicht' },
  { question: 'Was bedeutet LAN?', answers: ['Local Area Network'], category: 'PC', difficulty: 'leicht' },
  { question: 'Was bedeutet NPC?', answers: ['Non Player Character', 'Nicht-Spieler-Charakter'], category: 'Genres', difficulty: 'leicht' },
  { question: 'Was bedeutet DPS?', answers: ['Damage per Second', 'Schaden pro Sekunde'], category: 'Genres', difficulty: 'leicht' },
  { question: 'Wie heißt die Plattform von Epic Games?', answers: ['Epic Games Store'], category: 'PC', difficulty: 'leicht' },
  { question: 'Wie heißt EAs Launcher heute?', answers: ['EA app', 'EA App'], category: 'PC', difficulty: 'mittel' },
  { question: 'Welche Plattform nutzt Ubisoft als Launcher?', answers: ['Ubisoft Connect'], category: 'PC', difficulty: 'mittel' },
  { question: 'Wie heißt Blizzards Launcher?', answers: ['Battle.net', 'Battlenet'], category: 'PC', difficulty: 'leicht' },
  { question: 'Welche Firma entwickelte League of Legends?', answers: ['Riot Games', 'Riot'], category: 'MOBA', difficulty: 'leicht' },
  { question: 'Welche Karte aus LoL hat drei Lanes?', answers: ['Summoners Rift', "Summoner's Rift", 'Kluft der Beschwörer'], category: 'MOBA', difficulty: 'leicht' },
  { question: 'Wie heißt die neutrale LoL-Kreatur, die Baron-Buff gibt?', answers: ['Baron Nashor', 'Baron'], category: 'MOBA', difficulty: 'leicht' },
  { question: 'Wie heißt die Dota-2-Kreatur mit Aegis?', answers: ['Roshan'], category: 'MOBA', difficulty: 'mittel' },
  { question: 'Wie heißt die Datenbank-/Mod-Plattform von Valve-Spielen?', answers: ['Steam Workshop', 'Workshop'], category: 'PC', difficulty: 'leicht' },
  { question: 'Welche Engine wurde durch Doom berühmt?', answers: ['id Tech', 'Doom Engine'], category: 'Technik', difficulty: 'mittel' },
  { question: 'Welche Firma entwickelte Doom?', answers: ['id Software'], category: 'Shooter', difficulty: 'leicht' },
  { question: 'Wie heißt der Doom-Protagonist im Meme?', answers: ['Doomguy', 'Doom Slayer'], category: 'Shooter', difficulty: 'leicht' },
  { question: 'Welches Spiel gilt als früher populärer Ego-Shooter vor Doom?', answers: ['Wolfenstein 3D', 'Wolfenstein'], category: 'Shooter', difficulty: 'mittel' },
  { question: 'Welche Reihe hat Lara Croft als Heldin?', answers: ['Tomb Raider'], category: 'Adventure', difficulty: 'leicht' },
  { question: 'Welche Reihe hat Nathan Drake?', answers: ['Uncharted'], category: 'Adventure', difficulty: 'leicht' },
  { question: 'Wie heißt Kratos Sohn in God of War?', answers: ['Atreus'], category: 'Adventure', difficulty: 'leicht' },
  { question: 'Welche Waffe nutzt Kratos in den neuen God-of-War-Spielen prominent?', answers: ['Leviathan-Axt', 'Leviathan Axe'], category: 'Adventure', difficulty: 'mittel' },
  { question: 'Wie heißt die Zombie-Pilzinfektion in The Last of Us?', answers: ['Cordyceps'], category: 'Adventure', difficulty: 'mittel' },
  { question: 'Welche Firma entwickelte The Last of Us?', answers: ['Naughty Dog'], category: 'Adventure', difficulty: 'leicht' },
  { question: 'Wie heißt der Waschbär-Polizist aus Resident Evil 2?', answers: ['Leon', 'Leon Kennedy', 'Leon S. Kennedy'], category: 'Horror', difficulty: 'leicht' },
  { question: 'Welche Umbrella-Stadt geht in Resident Evil unter?', answers: ['Raccoon City'], category: 'Horror', difficulty: 'leicht' },
  { question: 'Wie heißt das Funkgerät-Geräusch in Silent Hill oft als Warnsignal?', answers: ['Radio', 'Rauschen'], category: 'Horror', difficulty: 'mittel' },
  { question: 'Welche Reihe hat den Ort Silent Hill?', answers: ['Silent Hill'], category: 'Horror', difficulty: 'leicht' },
  { question: 'Wie heißt das japanische Monsterfang-Spiel von Game Freak?', answers: ['Pokémon', 'Pokemon'], category: 'Nintendo', difficulty: 'leicht' },
  { question: 'Wie heißt das erste Pokémon im Pokédex?', answers: ['Bisasam', 'Bulbasaur'], category: 'Nintendo', difficulty: 'mittel' },
  { question: 'Wie entwickelt sich Glumanda final?', answers: ['Glurak', 'Charizard'], category: 'Nintendo', difficulty: 'leicht' },
  { question: 'Welche Typ-Attacke ist gegen Wasser effektiv?', answers: ['Elektro', 'Pflanze', 'Electric', 'Grass'], category: 'Nintendo', difficulty: 'leicht' },
  { question: 'Wie heißt der gelbe Pokémon-Maskottchen?', answers: ['Pikachu'], category: 'Nintendo', difficulty: 'leicht' },
  { question: 'Welche Firma entwickelte Minecraft ursprünglich?', answers: ['Mojang'], category: 'Sandbox', difficulty: 'leicht' },
  { question: 'Wer war der ursprüngliche Hauptentwickler von Minecraft?', answers: ['Notch', 'Markus Persson'], category: 'Sandbox', difficulty: 'mittel' },
  { question: 'Welche Sandbox-Serie hat Garrys Mod hervorgebracht?', answers: ['Half-Life 2', 'Source'], category: 'Sandbox', difficulty: 'mittel' },
  { question: 'Welche Engine nutzt Garrys Mod?', answers: ['Source', 'Source Engine'], category: 'Technik', difficulty: 'leicht' },
];
