export interface ScribbleWordSeed {
  word: string;
  difficulty: 'leicht' | 'mittel' | 'schwer';
}

const words = (difficulty: ScribbleWordSeed['difficulty'], list: string[]): ScribbleWordSeed[] =>
  list.map((word) => ({ word, difficulty }));

export const DEFAULT_SCRIBBLE_WORDS: ScribbleWordSeed[] = [
  ...words('leicht', [
    'Maus', 'Tastatur', 'Headset', 'Bildschirm', 'Pizza', 'Cola', 'Chips', 'Controller',
    'Sonne', 'Mond', 'Stern', 'Baum', 'Haus', 'Auto', 'Fahrrad', 'Katze', 'Hund', 'Fisch',
    'Vogel', 'Blume', 'Apfel', 'Banane', 'Pilz', 'Roboter', 'Rakete', 'Ballon', 'Regenschirm',
    'Brille', 'Hut', 'Schuh', 'Uhr', 'Herz', 'Krone', 'Schwert', 'Schild', 'Burg', 'Drache',
    'Gespenst', 'Kürbis', 'Schneemann', 'Regenbogen', 'Wolke', 'Blitz', 'Feuer', 'Wasser',
    'Berg', 'Insel', 'Boot', 'Flugzeug', 'Zug', 'Ampel', 'Brücke', 'Leiter', 'Zelt', 'Lagerfeuer',
    // Zusätzliche Wörter, geprüft gegen die öffentliche deutsche Wortliste von skribbl.io
    // (https://github.com/skribbliohints/skribbliohints.github.io), ohne Marken, reale
    // Personen, urheberrechtlich geschützte Figuren und Länder/Städte.
    'Aal', 'Abend', 'Abfall', 'Abzug', 'Achsel', 'Adler', 'Affe', 'Agent', 'Ahorn', 'Aimbot',
    'Airbag', 'Akne', 'Aktion', 'Alarm', 'Allee', 'Alpaka', 'Amboss', 'Ameise', 'Amor',
    'Amsel', 'Ananas', 'Anime', 'Anubis', 'Anwalt', 'Anzug', 'Apollo', 'App', 'Arbeit', 'Arm',
    'Artist', 'Arzt', 'Asche', 'Ass', 'Ast', 'Atem', 'Athene', 'Athlet', 'Atlas', 'Atom',
    'Aufzug', 'Auge', 'Auster', 'Autor', 'Axt', 'Ayran', 'Baby', 'Bagel', 'Bagger', 'Balkon',
    'Ball', 'Bambus', 'Band', 'Banjo', 'Bank', 'Banner', 'Bar', 'Barbar', 'Barsch', 'Bart',
    'Basar', 'Basis', 'Bass', 'Bauch', 'Bauer', 'Beamer', 'Becken', 'Beine', 'Benzin', 'Besen',
    'Bett', 'Beule', 'Beute', 'Bibel', 'Biber', 'Biene', 'Bier', 'Bikini', 'Bingo', 'Birke',
    'Birne', 'Bison', 'Biss', 'Bizeps', 'Blase', 'Blatt', 'Blut', 'Blüte', 'Bock', 'Bogen',
    'Bohne', 'Bohrer', 'Boje', 'Bombe', 'Bonbon', 'Bongo', 'Bonsai', 'Boss', 'Box', 'Boxer',
    'Brause', 'Braut', 'Brett', 'Brezel', 'Bronze', 'Brot', 'Bruch', 'Brust', 'Buch', 'Buddha',
    'Buffet', 'Bulle', 'Bus', 'Busch', 'Butter', 'Bäcker', 'Bär', 'Böller', 'Büffel', 'Bühne',
    'Büro', 'Bürste', 'Cajon', 'Cello', 'Chaos', 'Chat', 'Chef', 'Chemie', 'Chor', 'Clogs',
    'Clown', 'Comic', 'Corgi', 'Couch', 'Cousin', 'Cowboy', 'Creme', 'Crocs', 'Curry',
    'Cyborg', 'Dach', 'Dachs', 'Dame', 'Damm', 'Dampf', 'Darm', 'Darts', 'Dattel', 'Daumen',
    'Daune', 'Decke', 'Deckel', 'Degen', 'Delfin', 'Delle', 'Dieb', 'Diener', 'Diesel',
    'Dikdik', 'Dill', 'Diplom', 'Dirndl', 'Disco', 'Diva', 'Diät', 'Doktor', 'Dolch', 'Dollar',
    'Domino', 'Donner', 'Donut', 'Dorf', 'Dorn', 'Dose', 'Drama', 'Dreck', 'Duell', 'Durst',
    'Dusche', 'Dynamo', 'Dämon', 'Döner', 'Düne', 'Dürre', 'Ebbe', 'Eber', 'Ecke', 'Eclair',
    'Efeu', 'Ei', 'Eiche', 'Eichel', 'Eigelb', 'Eimer', 'Einrad', 'Einöde', 'Eis', 'Eisbär',
    'Eisen', 'Eistee', 'Elch', 'Elfe', 'Elle', 'Elster', 'Eltern', 'Emoji', 'Emu', 'Ende',
    'Engel', 'Ente', 'Erbsen', 'Erde', 'Esel', 'Essen', 'Essig', 'Eule', 'Euro', 'Euter',
    'Fabrik', 'Fackel', 'Fahrer', 'Falle', 'Falte', 'Fan', 'Farbe', 'Farn', 'Fass', 'Faust',
    'Feder', 'Fee', 'Fehler', 'Feld', 'Fell', 'Felsen', 'Ferien', 'Ferkel', 'Ferse', 'Fieber',
    'Figur', 'Film', 'Filter', 'Finger', 'Flagge', 'Fleck', 'Fliege', 'Fliese', 'Floh', 'Floß',
    'Fluss', 'Flut', 'Flöte', 'Flügel', 'Form', 'Fossil', 'Frau', 'Freund', 'Frosch', 'Frost',
    'Frucht', 'Fuchs', 'Funke', 'Fussel', 'Fuß', 'Fächer', 'Föhn', 'Fühler', 'Gabel', 'Gang',
    'Gans', 'Garage', 'Garn', 'Garten', 'Gas', 'Gasse', 'Gebiss', 'Gebäck', 'Gefahr', 'Gehirn',
    'Geier', 'Geige', 'Geist', 'Geld', 'Gelee', 'Gemüse', 'Genie', 'Gepard', 'Gepäck',
    'Geröll', 'Gewalt', 'Gewehr', 'Geweih', 'Gewürz', 'Geysir', 'Gier', 'Gift', 'Gips',
    'Gitter', 'Glanz', 'Glas', 'Glatze', 'Globus', 'Glocke', 'Glut', 'Glück', 'Gnom', 'Goblin',
    'Gold', 'Golem', 'Golf', 'Gondel', 'Gong', 'Gott', 'Gouda', 'Grab', 'Grafik', 'Gras',
    'Grenze', 'Grill', 'Grille', 'Grotte', 'Grube', 'Guiro', 'Gully', 'Gummi', 'Gurke',
    'Göttin', 'Gürtel', 'Haare', 'Hacker', 'Hades', 'Hafen', 'Hagel', 'Hahn', 'Hai', 'Haken',
    'Hals', 'Hammer', 'Hand', 'Handy', 'Hantel', 'Harfe', 'Harz', 'Hase', 'Haut', 'Hecht',
    'Hecke', 'Held', 'Helium', 'Helm', 'Henker', 'Henne', 'Herbst', 'Herde', 'Hering',
    'Hermes', 'Hexe', 'Himmel', 'Hippie', 'Hirsch', 'Hirte', 'Hitze', 'Hocker', 'Hockey',
    'Holz', 'Honig', 'Horn', 'Hose', 'Hotdog', 'Hotel', 'Huf', 'Huhn', 'Hummel', 'Hummer',
    'Hunger', 'Hupe', 'Husky', 'Hydra', 'Hyäne', 'Hälfte', 'Höhle', 'Hölle', 'Hüfte', 'Hügel',
    'Hürde', 'Hütte', 'Idee', 'Igel', 'Imker', 'Insekt', 'Inuit', 'Iris', 'Jacht', 'Jacke',
    'Jaguar', 'Jazz', 'Jeans', 'Jeep', 'Jesus', 'Jetski', 'Jo-Jo', 'Jodeln', 'Joker', 'Judo',
    'Junge', 'Juwel', 'Jäger', 'Kabel', 'Kabine', 'Kaffee', 'Kakao', 'Kaktus', 'Kamel',
    'Kamera', 'Kamin', 'Kamm', 'Kanone', 'Kanu', 'Kanzel', 'Kappe', 'Kapsel', 'Karate',
    'Karte', 'Kasino', 'Katana', 'Kater', 'Kaviar', 'Kazoo', 'Kebab', 'Kefir', 'Kegel',
    'Kehle', 'Keim', 'Keks', 'Keller', 'Kerze', 'Kessel', 'Kette', 'Keule', 'Kiefer', 'Kilt',
    'Kind', 'Kinn', 'Kino', 'Kirche', 'Kissen', 'Kiste', 'Kiwi', 'Klasse', 'Klaue', 'Kleber',
    'Kleid', 'Klinik', 'Klippe', 'Knast', 'Kneipe', 'Knete', 'Knie', 'Knopf', 'Knospe',
    'Knoten', 'Knödel', 'Koala', 'Kobra', 'Koch', 'Koffer', 'Kohl', 'Kohle', 'Kojote', 'Kokon',
    'Komet', 'Kopf', 'Kopie', 'Korb', 'Korken', 'Kostüm', 'Koto', 'Krabbe', 'Krake', 'Kran',
    'Kranz', 'Krebs', 'Kredit', 'Kreide', 'Kreis', 'Kreuz', 'Krieg', 'Krug', 'Kruste', 'Krähe',
    'Kröte', 'Kuchen', 'Kugel', 'Kuh', 'Kunde', 'Kunst', 'Kupfer', 'Kuppel', 'Kurve', 'Käfer',
    'Käfig', 'Käse', 'Köcher', 'Köder', 'König', 'Küche', 'Küste', 'Lachs', 'Lama', 'Lamm',
    'Lampe', 'Land', 'Lanze', 'Laptop', 'Laser', 'Lasso', 'Laute', 'Lava', 'Lawine', 'Leber',
    'Leck', 'Leder', 'Lehm', 'Lehrer', 'Leiche', 'Leine', 'Lemur', 'Liane', 'Licht', 'Liebe',
    'Lilie', 'Limbo', 'Lineal', 'Linie', 'Link', 'Linse', 'Lippen', 'Loch', 'Locher', 'Logo',
    'Loki', 'Luchs', 'Luke', 'Lunge', 'Lupe', 'Läufer', 'Löffel', 'Löwe', 'Lüfter', 'Made',
    'Mafia', 'Magie', 'Magier', 'Magma', 'Magnet', 'Mais', 'Maki', 'Maler', 'Mammut', 'Mandel',
    'Manege', 'Mann', 'Mantel', 'Marke', 'Markt', 'Mars', 'Maske', 'Matsch', 'Maurer', 'Maut',
    'Medusa', 'Meer', 'Melone', 'Meme', 'Merkur', 'Messer', 'Metall', 'Mikado', 'Milch',
    'Mine', 'Minute', 'Minze', 'Mixer', 'Model', 'Mohn', 'Montag', 'Moos', 'Mopp', 'Mops',
    'Morgen', 'Mosaik', 'Motor', 'Motte', 'Muffin', 'Mumie', 'Mund', 'Museum', 'Musik',
    'Muskel', 'Mutter', 'Mähne', 'Möbel', 'Möhre', 'Mönch', 'Mörder', 'Möwe', 'Mücke',
    'Müller', 'Münze', 'Müsli', 'Mütze', 'Nachos', 'Nacht', 'Nacken', 'Nadel', 'Nagel',
    'Narbe', 'Narr', 'Narwal', 'Nase', 'Natur', 'Navy', 'Nebel', 'Nepal', 'Neptun', 'Nerd',
    'Nest', 'Netz', 'Nickel', 'Niere', 'Ninja', 'Nitro', 'Nixe', 'Nonne', 'Norden', 'Noten',
    'Nudel', 'Nuss', 'Oase', 'Ober', 'Oboe', 'Odin', 'Ofen', 'Ohr', 'Olive', 'Onkel', 'Oper',
    'Opera', 'Opfer', 'Orange', 'Orbit', 'Orca', 'Ordner', 'Organ', 'Orgel', 'Osten', 'Ostern',
    'Ostsee', 'Otter', 'Oval', 'Ozean', 'Ozelot', 'Palast', 'Palme', 'Pan', 'Panda', 'Panzer',
    'Papaya', 'Papier', 'Pappe', 'Papst', 'Parade', 'Parfüm', 'Park', 'Party', 'Pasta',
    'Pauke', 'Pause', 'Pavian', 'Pech', 'Pedal', 'Pendel', 'Penne', 'Perle', 'Person', 'Pfad',
    'Pfand', 'Pfanne', 'Pfau', 'Pfeife', 'Pfeil', 'Pferd', 'Pflug', 'Pfote', 'Pfund', 'Pfütze',
    'Pharao', 'Pi', 'Pickel', 'Pilot', 'Pinata', 'Pinsel', 'Pirat', 'Pixel', 'Planet',
    'Planke', 'Pluto', 'Podium', 'Pokal', 'Poker', 'Pollen', 'Polo', 'Pony', 'Popel', 'Portal',
    'Poster', 'Preis', 'Prinz', 'Prisma', 'Profi', 'Pudel', 'Puder', 'Puma', 'Punker', 'Punkt',
    'Punkte', 'Punsch', 'Puppe', 'Pups', 'Puzzle', 'Python', 'Quad', 'Qualle', 'Quark',
    'Quelle', 'Queue', 'Rad', 'Radar', 'Radio', 'Rahmen', 'Rampe', 'Rapper', 'Ratte', 'Rauch',
    'Raum', 'Raupe', 'Razzia', 'Rechen', 'Redner', 'Regal', 'Regen', 'Reh', 'Reibe', 'Reifen',
    'Reis', 'Reise', 'Rektor', 'Rennen', 'Reptil', 'Rezept', 'Riese', 'Ring', 'Rippe',
    'Risiko', 'Ritter', 'Robbe', 'Robe', 'Rochen', 'Rock', 'Rodeo', 'Rohr', 'Roller', 'Rom',
    'Roman', 'Rose', 'Rosine', 'Rubin', 'Ruder', 'Rugby', 'Ruhe', 'Rune', 'Räuber', 'Rübe',
    'Rücken', 'Rührei', 'Rüssel', 'Safari', 'Safe', 'Saft', 'Sahne', 'Salami', 'Salat',
    'Salon', 'Salz', 'Samen', 'Sand', 'Saphir', 'Sarg', 'Sattel', 'Saturn', 'Sau', 'Sauna',
    'Schach', 'Schaf', 'Schal', 'Schatz', 'Schere', 'Schilf', 'Schnee', 'Schock', 'Schoß',
    'Schule', 'Schwan', 'See', 'Seekuh', 'Segway', 'Seife', 'Seil', 'Seite', 'Selfie', 'Senf',
    'Server', 'Sessel', 'Seuche', 'Shisha', 'Shogun', 'Shorts', 'Sichel', 'Sieg', 'Silber',
    'Silo', 'Sitar', 'Ski', 'Slalom', 'Slinky', 'Snack', 'Sockel', 'Socken', 'Sohn', 'Soldat',
    'Sommer', 'Soße', 'Spagat', 'Spaten', 'Specht', 'Speck', 'Speer', 'Sphinx', 'Spiel',
    'Spieß', 'Spinat', 'Spinne', 'Spion', 'Spore', 'Sport', 'Spule', 'Stab', 'Stadt', 'Stall',
    'Stativ', 'Statue', 'Stau', 'Staub', 'Stein', 'Stereo', 'Stift', 'Stirn', 'Stock', 'Stoff',
    'Storch', 'Strand', 'Strauß', 'Straße', 'Studio', 'Stuhl', 'Sturm', 'Sturz', 'Styx',
    'Sudoku', 'Sumo', 'Sumpf', 'Suppe', 'Sushi', 'Säbel', 'Säge', 'Säule', 'Säure', 'Süden',
    'Südpol', 'Tabak', 'Tablet', 'Tacker', 'Taco', 'Tafel', 'Tag', 'Taille', 'Tal', 'Tandem',
    'Tank', 'Tapete', 'Tasche', 'Taser', 'Tasse', 'Tattoo', 'Tau', 'Taube', 'Taxi', 'Tee',
    'Tee-Ei', 'Teich', 'Teig', 'Teller', 'Tennis', 'Tetris', 'Teufel', 'Text', 'Thor', 'Thron',
    'Tiegel', 'Tiger', 'TikTok', 'Tinte', 'Tipi', 'Tisch', 'Titan', 'Toast', 'Tomate', 'Topf',
    'Tor', 'Torte', 'Totem', 'Traum', 'Trend', 'Troll', 'Truhe', 'Träne', 'Tuba', 'Tukan',
    'Tulpe', 'Tumor', 'Tundra', 'Tunnel', 'Turban', 'Turm', 'Tutu', 'Töne', 'Tür', 'U-Bahn',
    'U-Boot', 'Ufer', 'Umhang', 'Unfall', 'Uranus', 'Urlaub', 'Vakuum', 'Vampir', 'Van',
    'Vater', 'Vene', 'Venus', 'Video', 'Villa', 'Virus', 'Vision', 'Vodka', 'Voodoo', 'W-LAN',
    'Waage', 'Wachs', 'Wade', 'Waffe', 'Waffel', 'Wahl', 'Wal', 'Wald', 'Wand', 'Wange',
    'Wanze', 'Warze', 'Wecker', 'Weide', 'Wein', 'Weizen', 'Welle', 'Welpe', 'Welt', 'Wespe',
    'Weste', 'Westen', 'Wetter', 'Widder', 'Wiege', 'Wiese', 'Wiesel', 'Wimper', 'Wind',
    'Windel', 'Winter', 'Winzer', 'Wippe', 'Wirbel', 'Wolf', 'Wolle', 'Wort', 'Wunde', 'Wurm',
    'Wurst', 'Wurzel', 'Yeti', 'Yoga', 'Zahl', 'Zahn', 'Zange', 'Zaun', 'Zebra', 'Zecke',
    'Zeh', 'Zelle', 'Zement', 'Zeuge', 'Zeus', 'Ziege', 'Ziel', 'Zikade', 'Zirkel', 'Zirkus',
    'Zitze', 'Zoll', 'Zombie', 'Zoo', 'Zopf', 'Zucker', 'Zunge', 'Zweig', 'Zwerg', 'Zyklop',
    'Zügel', 'Ärmel', 'Öl',
  ]),
  ...words('mittel', [
    'Respawn', 'Lootbox', 'Ladebildschirm', 'Netzwerkkabel', 'Grafikkarte', 'Bluescreen',
    'Energydrink', 'Gamepad', 'Sitzsack', 'Verlängerungskabel', 'Mehrfachsteckdose',
    'Router', 'Headset-Mikrofon', 'Joystick', 'Würfel', 'Schachbrett', 'Vogelscheuche',
    'Windmühle', 'Leuchtturm', 'Vulkan', 'Gletscher', 'Wüste', 'Dschungel', 'Piratenschiff',
    'Schatzkarte', 'Zauberstab', 'Kristallkugel', 'Teppich', 'Kronleuchter', 'Spinnennetz',
    'Fallschirm', 'Astronaut', 'Satellit', 'Teleskop', 'Kompass', 'Anker', 'Handschellen',
    'Skateboard', 'Trampolin', 'Karussell', 'Achterbahn', 'Zirkuszelt', 'Jongleur',
    // Zusätzliche Wörter aus der skribbl.io-Wortliste (siehe Kommentar oben bei 'leicht')
    'Aasfresser', 'Abendessen', 'Abflussrohr', 'Abgrund', 'Abonnement', 'Abrissbirne',
    'Abschluss', 'Absperrband', 'Achselhöhle', 'Achteck', 'Adamsapfel', 'Addition',
    'Adrenalin', 'Afrofrisur', 'Aftershave', 'AirPods', 'Akkordeon', 'Albatros', 'Albtraum',
    'Alchemist', 'Alkohol', 'Allergie', 'Alligator', 'Alphabet', 'Alphorn', 'Altersheim',
    'Alufolie', 'Ameisenbär', 'Ameisenigel', 'Amethyst', 'Anakonda', 'Analphabet', 'Anatomie',
    'Anfänger', 'Anführer', 'Angebot', 'Angestellter', 'Anglerfisch', 'Anhalter', 'Anhänger',
    'Animation', 'Antilope', 'Antivirus', 'Anzeige', 'Apfelkern', 'Apfelkuchen', 'Apfelsaft',
    'Apokalypse', 'Apotheker', 'Aprikose', 'Aquarium', 'Arbeiter', 'Architekt', 'Archäologe',
    'Aristokrat', 'Armband', 'Armbanduhr', 'Armbrust', 'Armdrücken', 'Armleuchter', 'Arterie',
    'Artischocke', 'Artischocken', 'Arztkoffer', 'Aschenbecher', 'Aschenputtel', 'Asterisk',
    'Asteroid', 'Astgabel', 'Atlantis', 'Atmosphäre', 'Atombombe', 'Atomkern', 'Atompilz',
    'Atomuhr', 'Aubergine', 'Aufhänger', 'Aufkleber', 'Auflaufform', 'Aufnahme', 'Augapfel',
    'Augenbinde', 'Augenbraue', 'Augenklappe', 'Augenlid', 'Augenringe', 'Auspuff', 'Autobahn',
    'Autoclicker', 'Autogramm', 'Autoradio', 'Avocado', 'Axolotl', 'Babyfon', 'Backenzahn',
    'Badeanzug', 'Badekappe', 'Bademantel', 'Bademeister', 'Badewanne', 'Badezimmer',
    'Badminton', 'Baguette', 'Bahnhof', 'Bahnschiene', 'Bajonett', 'Baklava', 'Ballett',
    'Bandnudel', 'Bankdrücken', 'Bankier', 'Barbecue', 'Barbier', 'Barcode', 'Bargeld',
    'Barkeeper', 'Baseball', 'Basilikum', 'Baskenmütze', 'Basketball', 'Batterie',
    'Bauarbeiter', 'Bauchnabel', 'Bauchredner', 'Bauernhof', 'Baumhaus', 'Baumkrone',
    'Baumkuchen', 'Baumschule', 'Baumstamm', 'Baumstumpf', 'Baumwolle', 'Beatbox', 'Bedienung',
    'Beerdigung', 'Befehlshaber', 'Beförderung', 'Beinrasur', 'Bergkette', 'Bernstein',
    'Berühmtheit', 'Besenkammer', 'Besenstiel', 'Bestatter', 'Bestrafung', 'Bettdecke',
    'Bettwanze', 'Beziehung', 'Bibliothekar', 'Bienenstich', 'Bienenstock', 'Bildhauer',
    'Billard', 'Biologie', 'Biotonne', 'Blasebalg', 'Blattlaus', 'Blaubeere', 'Blaulicht',
    'Blaupause', 'Bleiche', 'Bleistift', 'Blindenhund', 'Blitzer', 'Blizzard', 'Blumenkohl',
    'Blumenstrauß', 'Blutegel', 'Bluterguss', 'Blutspende', 'Bodybuilding', 'Bogenschütze',
    'Bohnenstange', 'Bowling', 'Braille', 'Brathering', 'Bratsche', 'Bratwurst', 'Breakdance',
    'Brecheisen', 'Brennnessel', 'Brettspiel', 'Briefkasten', 'Briefkopf', 'Brieftaube',
    'Briefträger', 'Brieföffner', 'Brillenetui', 'Brocken', 'Brokkoli', 'Brombeere', 'Brownie',
    'Bruderherz', 'Brunnen', 'Brusthaare', 'Brustkorb', 'Bräutigam', 'Brüllaffe', 'Bullauge',
    'Bulldozer', 'Bullseye', 'Bumerang', 'Bundestag', 'Buntstift', 'Burggraben', 'Burgruine',
    'Burrito', 'Busbahnhof', 'Busenfreund', 'Busfahrer', 'Buttermesser', 'Buttermilch',
    'Bäckerei', 'Bärenfalle', 'Bärenhunger', 'Bärlauch', 'Bösewicht', 'Bücherei',
    'Bücherregal', 'Bücherwurm', 'Bügeleisen', 'Bürgersteig', 'Büroklammer', 'CD-Player',
    'Cabriolet', 'Calamari', 'Callcenter', 'Camping', 'Cappuccino', 'Cartoon', 'Cerberus',
    'Cerealien', 'Champagner', 'Champion', 'Chamäleon', 'Cheerleader', 'Cheeseburger',
    'Chihuahua', 'Chinchilla', 'Chirurg', 'ClickBait', 'Clownfisch', 'Cockpit', 'Cocktail',
    'Coffeeshop', 'Comicbuch', 'Community', 'Computer', 'Corrida', 'Countdown', 'Cranberry',
    'Cricket', 'Croissant', 'Cupcake', 'DVD-Player', 'Dachboden', 'Dachfenster',
    'Dachgeschoss', 'Dachschaden', 'Dalmatiner', 'Damenbart', 'Dampflok', 'Darsteller',
    'Denkzettel', 'Deodorant', 'Dessert', 'Detektiv', 'Diabolo', 'Diagonale', 'Diagramm',
    'Diamant', 'Dickkopf', 'Didgeridoo', 'Dienstag', 'Dinosaurier', 'Dionysos', 'Dirigent',
    'Discord', 'Diskette', 'Distanz', 'Division', 'Dompteur', 'Donnerstag', 'Dorfbewohner',
    'Dornröschen', 'Dosenöffner', 'Dreadlocks', 'Drehtür', 'Dreieck', 'Dreirad', 'Drillinge',
    'Drucker', 'Dudelsack', 'Duschkopf', 'Dynamit', 'E-Gitarre', 'Edelstein', 'Ehefrau',
    'Ehemann', 'Eichhörnchen', 'Eidechse', 'Eierbecher', 'Eierlikör', 'Eiersuchen',
    'Eingabestift', 'Einhorn', 'Einhornwal', 'Einschlag', 'Einsiedler', 'Eintopf',
    'Einzelhandel', 'Eisberg', 'Eisbrecher', 'Eischnee', 'Eisfischen', 'Eiskaffee',
    'Eisverkäufer', 'Eiszapfen', 'Eiszeit', 'Elefant', 'Elektriker', 'Elektroauto', 'Elektron',
    'Elfenbein', 'Ellbogen', 'Entdecker', 'Entensuppe', 'Erdbeben', 'Erdbeere', 'Erdkern',
    'Erdmännchen', 'Erdnuss', 'Erdnussflips', 'Erfindung', 'Erkältung', 'Erwachsener',
    'Eselsbrücke', 'Eselsohr', 'Espresso', 'Essiggurke', 'Esspapier', 'Essstäbchen',
    'Etagenbett', 'Evolution', 'Excalibur', 'Experiment', 'Explosion', 'Fadenkreuz',
    'Fahnenstange', 'Fahrbahn', 'Fahrkarte', 'Fahrradkette', 'Fahrwerk', 'Fahrzeug', 'Falafel',
    'Falltür', 'Falschgeld', 'Familie', 'Farbpalette', 'Farbroller', 'Fassade', 'Fastfood',
    'Faultier', 'Faustkampf', 'Fechten', 'Federball', 'Feierabend', 'Feldstecher', 'Fenster',
    'Fensterbank', 'Fernglas', 'Fernrohr', 'Fernseher', 'Fernsehturm', 'Festival', 'Festung',
    'Fettuccine', 'Feueralarm', 'Feuerball', 'Feuerlöscher', 'Feuerstelle', 'Feuerwache',
    'Feuerwerk', 'Feuerzeug', 'Filmemacher', 'Filmriss', 'Fingerhut', 'Fingernagel',
    'Fingerpuppe', 'Fingerspitze', 'Fischer', 'Fischernetz', 'Fischgräte', 'Flachdach',
    'Flamingo', 'Flammkuchen', 'Flasche', 'Flaschenhals', 'Flaschenzug', 'Fledermaus',
    'Fleisch', 'Fliegenpilz', 'Fließband', 'Flipper', 'Flohmarkt', 'Florist', 'Flughafen',
    'Fluglinie', 'Flutlicht', 'Forelle', 'Fotograf', 'Freibad', 'Freitag', 'Freizeitpark',
    'Frettchen', 'Frieden', 'Friedhof', 'Frisbee', 'Friseur', 'Fritten', 'Froschkönig',
    'Frutarier', 'Frühling', 'Frühstück', 'Fuchsschwanz', 'Furzkissen', 'Fußball', 'Fußende',
    'Fußmatte', 'Fässchen', 'Führerschein', 'Gabelstapler', 'Galaxie', 'Gangster', 'Garderobe',
    'Garnele', 'Gartenschere', 'Gasmaske', 'Gazelle', 'Geburtstag', 'Gebäude', 'Gedicht',
    'Gefangener', 'Gefängnis', 'Geheimnis', 'Gehirnwäsche', 'Geisterbahn', 'Geistesblitz',
    'Gekritzel', 'Geldautomat', 'Geldbeutel', 'Geldwäsche', 'Generator', 'Gentleman',
    'Geodreieck', 'Geografie', 'Geologe', 'Gepäckträger', 'Geschenk', 'Geschlecht', 'Geschäft',
    'Gesicht', 'Gesundheit', 'Getreide', 'Getränk', 'Gewinner', 'Gewitter', 'Gewächshaus',
    'Gießkanne', 'Giftmüll', 'Giftzwerg', 'Gipfelkreuz', 'Giraffe', 'Gitarre', 'Gladiator',
    'Glitzer', 'Glockenblume', 'Glockenspiel', 'Glückskeks', 'Glückspilz', 'Glücksrad',
    'Glücksspiel', 'Glühbirne', 'Glühwein', 'Glühwürmchen', 'Goldbarren', 'Goldesel',
    'Goldfisch', 'Goldkette', 'Goldlöckchen', 'Goldnugget', 'Goldtopf', 'Golfwagen', 'Gorilla',
    'Gourmet', 'Grabmal', 'Grabstein', 'Graffiti', 'Grammofon', 'Granatapfel', 'Granate',
    'Grapefruit', 'Graphit', 'Grashüpfer', 'Grillen', 'Grizzly', 'Groschen', 'Großmutter',
    'Großvater', 'Gugelhupf', 'Guillotine', 'Gummiband', 'Gummibärchen', 'Gummiente',
    'Gymnasium', 'Gymnastik', 'Gänsefüßchen', 'Gänsehaut', 'Gärtner', 'Götterspeise',
    'Gürteltier', 'Güterwagen', 'Haarband', 'Haarfarbe', 'Haarschnitt', 'Haarschuppen',
    'Haarspange', 'Haarspray', 'Hackbraten', 'Hafenbecken', 'Halbinsel', 'Halbkreis',
    'Halbleiter', 'Halbmond', 'Halsband', 'Halskette', 'Halskrause', 'Haltestelle',
    'Hamburger', 'Hammerhai', 'Hampelmann', 'Hamster', 'Hamsterrad', 'Handfläche',
    'Handgelenk', 'Handkuss', 'Handschlag', 'Handschuh', 'Handtuch', 'Harpune', 'Haselnuss',
    'Hashtag', 'Hauptschule', 'Hausmeister', 'Hausnummer', 'Hausschuhe', 'Hawaiihemd',
    'Hebamme', 'Heckspoiler', 'Heizung', 'Helikopter', 'Herkules', 'Herzschlag', 'Heuschrecke',
    'Hexenschuss', 'Hieroglyphen', 'Highlighter', 'Himbeere', 'Himmelbett', 'Hipster',
    'Hirschkäfer', 'Hochstapler', 'Hochzeit', 'Hologramm', 'Holzfäller', 'Holzscheit',
    'Honiglöffel', 'Honigwabe', 'Horizont', 'Hosenstall', 'Hosentasche', 'Hubraum', 'Hufeisen',
    'Hundehütte', 'Hydrant', 'Hähnchen', 'Hängebrücke', 'Hängematte', 'Häuptling',
    'Höhenangst', 'Höhlenmensch', 'Höllenhund', 'Hörgerät', 'Hörtest', 'Hühnchen', 'Hüpfburg',
    'Hüpfkästchen', 'Hürdenlauf', 'Indianer', 'Ingenieur', 'Inhalator', 'Injektion',
    'Inlineskates', 'Internet', 'Interview', 'Invasion', 'Jagdziel', 'Jahrbuch', 'Jahreszeit',
    'Jalapeno', 'Joghurt', 'Journalist', 'Jupiter', 'Juwelier', 'Kabelsalat', 'Kakerlake',
    'Kaktuseis', 'Kalender', 'Kameramann', 'Kanalisation', 'Kaninchen', 'Kanister',
    'Kanonenkugel', 'Kapitän', 'Karamell', 'Karaoke', 'Karneval', 'Karotte', 'Karpfen',
    'Karteikasten', 'Kartenhaus', 'Kartenspiel', 'Kartoffel', 'Kastagnetten', 'Kastanie',
    'Katalog', 'Katamaran', 'Katapult', 'Katastrophe', 'Kathedrale', 'Katzenauge',
    'Katzengold', 'Katzenhai', 'Katzenklo', 'Katzenstreu', 'Kaugummi', 'Kaulquappe',
    'Kegelrobbe', 'Keksdose', 'Kellerassel', 'Kellner', 'Kendama', 'Kennzeichen',
    'Kerzendocht', 'Ketchup', 'Kettenhemd', 'Kettensäge', 'Keyboard', 'Kichererbse',
    'Kieselstein', 'Killerwal', 'Kinderarzt', 'Kindergarten', 'Kinderwagen', 'Kirschblüte',
    'Kirsche', 'Kitesurfen', 'Klappstuhl', 'Klarinette', 'Klavier', 'Klaviersaite',
    'Klebeband', 'Klebestift', 'Kleeblatt', 'Kleiderbügel', 'Kleinbus', 'Kleinkind',
    'Klemmbrett', 'Klempner', 'Kletterwand', 'Klimaanlage', 'Klingel', 'Klingelton',
    'Klobrille', 'Kloster', 'Knallfrosch', 'Kniebeuge', 'Kniffel', 'Knoblauch', 'Knochen',
    'Knöchel', 'Kofferraum', 'Kohlensäure', 'Kohlrabi', 'Kohlrübe', 'Kokosnuss', 'Kolibri',
    'Komiker', 'Kompassnadel', 'Komponist', 'Komödie', 'Konfetti', 'Konsole', 'Kontaktlinse',
    'Kontinent', 'Kontrabass', 'Kontrollturm', 'Konversation', 'Konzert', 'Kopfende',
    'Kopfhörer', 'Kopflaus', 'Kopftuch', 'Koralle', 'Korallenriff', 'Korkenzieher',
    'Koteletten', 'Kraftfeld', 'Kraftwerk', 'Kranich', 'Krankenhaus', 'Krankenwagen',
    'Krankheit', 'Kratzer', 'Krawatte', 'Kredithai', 'Kreditkarte', 'Kreisel', 'Kreuzfahrt',
    'Kreuzotter', 'Kreuzung', 'Krieger', 'Kriegsschiff', 'Kristall', 'Krokodil', 'Kronkorken',
    'Krummsäbel', 'Kuchengabel', 'Kuchenteig', 'Kuckuck', 'Kuckucksuhr', 'Kugelfisch',
    'Kugelstoßen', 'Kuhglocke', 'Kurzschluss', 'Känguru', 'Käseglocke', 'Käsekuchen',
    'Kätzchen', 'Königin', 'Körperteil', 'Küchentuch', 'Kühlmaschine', 'Kühlschrank',
    'Küstenwache', 'LKW-Fahrer', 'Laboratorium', 'Labyrinth', 'Lachgas', 'Lachgummi',
    'Ladebalken', 'Ladegerät', 'Lagerhaus', 'Lakritz', 'Lametta', 'Lampenfieber',
    'Lampenschirm', 'Landschaft', 'Langlauf', 'Lasagne', 'Laserpointer', 'Laterne',
    'Laubbläser', 'Laubhaufen', 'Laubsäge', 'Lautsprecher', 'Lautstärke', 'Lavalampe',
    'Lavendel', 'Lebensmittel', 'Lebkuchen', 'Lederhose', 'Leichtsinn', 'Leidenschaft',
    'Leiterbahn', 'Leiterwagen', 'Leopard', 'Lesezeichen', 'Leuchtstab', 'Lexikon', 'Libelle',
    'Lichterkette', 'Lichtschwert', 'Lidschatten', 'Liebesbrief', 'Lieferung', 'Liegestütze',
    'Limette', 'Limonade', 'Limousine', 'Lippenstift', 'Litfaßsäule', 'Litschi', 'Looping',
    'Lorbeeren', 'Lotterie', 'Luftmatratze', 'Luftschiff', 'Luftschlange', 'Luftschloss',
    'Lutscher', 'Lötlampe', 'Löwenzahn', 'Lüftung', 'Machete', 'Magazin', 'Mahlzeit',
    'Maibaum', 'Maikäfer', 'Maisfeld', 'Makkaroni', 'Malbuch', 'Malkasten', 'Mandarine',
    'Maniküre', 'Marathon', 'Margarine', 'Marienkäfer', 'Marimba', 'Marmelade', 'Marshmallow',
    'Marshmello', 'Marterpfahl', 'Maschine', 'Maskottchen', 'Mathematik', 'Matratze',
    'Matrjoschka', 'Matrose', 'Maulkorb', 'Maulwurf', 'Mausefalle', 'Mauspad', 'Mayonnaise',
    'Maßband', 'Maßstab', 'Mechaniker', 'Medaille', 'Medizin', 'Meerenge', 'Meerjungfrau',
    'Megafon', 'Meister', 'Messbecher', 'Meteorit', 'Meteorologe', 'Mikrofon', 'Mikroskop',
    'Mikrowelle', 'Milchmann', 'Milchshake', 'Milchstraße', 'Milchzahn', 'Militär',
    'Minesweeper', 'Minigolf', 'Minirock', 'Minotaurus', 'Mischpult', 'Mistelzweig',
    'Mistgabel', 'Mistkäfer', 'Mittagessen', 'Mittelfinger', 'Mitternacht', 'Mittwoch',
    'Modedesigner', 'Molkerei', 'Monobraue', 'Monokel', 'Monster', 'Morgenstern', 'Moskito',
    'Motherboard', 'Motorhaube', 'Motorrad', 'Mottenkugel', 'Mozzarella', 'Munition',
    'Murmelbahn', 'Murmeln', 'Murmeltier', 'Muschel', 'Muskelkater', 'Muskete', 'Muttermal',
    'Mädchen', 'Mähdrescher', 'Märchen', 'Müllabfuhr', 'Mülleimer', 'Müllkippe', 'Müllwagen',
    'Nachbar', 'Nachricht', 'Nachtclub', 'Nachthemd', 'Nachtisch', 'Nachtlicht', 'Nadelkissen',
    'Nagelfeile', 'Nagellack', 'Nagelpflege', 'Nagelschere', 'Nahrung', 'Nasenbluten',
    'Nasenbär', 'Nasenhaar', 'Nasenlöcher', 'Nasenring', 'Nasenspitze', 'Nashorn',
    'Neandertaler', 'Netzwerk', 'Neumond', 'Nichtraucher', 'Nilpferd', 'Nirwana', 'Nordpol',
    'Nordsee', 'Notizblock', 'Notizbuch', 'Nudelholz', 'Nussknacker', 'Nussschale',
    'Nähkästchen', 'Nähmaschine', 'Oberarm', 'Oberfläche', 'Oberschenkel', 'Oberteil',
    'Obstgarten', 'Obstkorb', 'Odysseus', 'Ohrenschmalz', 'Ohrhörer', 'Ohrmuschel', 'Ohrring',
    'Ohrwurm', 'Okarina', 'Oktoberfest', 'Oktopus', 'Olivenöl', 'Omelett', 'Operation',
    'Orang-Utan', 'Orchester', 'Orchidee', 'Origami', 'Osterglocke', 'Osterhase', 'Paintball',
    'Panflöte', 'Panther', 'Pantomime', 'Panzerband', 'Panzerfaust', 'Papagei', 'Paparazzi',
    'Papiertüte', 'Paprika', 'Paraglider', 'Parasit', 'Parcour', 'Parkplatz', 'Parkuhr',
    'Partnerlook', 'Passfoto', 'Passwort', 'Pastete', 'Patenonkel', 'Patriot', 'Patrone',
    'Pechvogel', 'Pegasus', 'Peitsche', 'Pelikan', 'Pendeluhr', 'Peperoni', 'Periskop',
    'Perücke', 'Petersilie', 'Pfadfinder', 'Pfannkuchen', 'Pfauenfeder', 'Pfeffer', 'Pfirsich',
    'Pflanze', 'Pflaster', 'Pflaume', 'Philosoph', 'Phoenix', 'Physalis', 'Picknick',
    'Pinguin', 'Pinienkerne', 'Pinzette', 'Pipette', 'Piranha', 'Pistazie', 'Pistole',
    'Pizzabote', 'Plankton', 'Planwagen', 'Plastiktüte', 'Plunder', 'Plätzchen', 'Pobacken',
    'Polarlicht', 'Polizei', 'Polizist', 'Polyphem', 'Pompeji', 'Popcorn', 'Porsche',
    'Portrait', 'Posaune', 'Poseidon', 'Postbote', 'Postkarte', 'Praline', 'Preiselbeere',
    'Preisschild', 'Priester', 'Prinzessin', 'Professor', 'Propeller', 'Proteinshake',
    'Protest', 'Prozent', 'Präsident', 'Prüfung', 'Psychologe', 'Publikum', 'Pudding',
    'Pullover', 'Punktestand', 'Puppenhaus', 'Purzelbaum', 'Pusteblume', 'Pyramide', 'Quadrat',
    'Quartal', 'Querflöte', 'Raclette', 'Radiergummi', 'Radieschen', 'Rapunzel', 'Rasenmäher',
    'Rasierer', 'Rasierklinge', 'Rasiermesser', 'Rasierschaum', 'Rasseln', 'Ratatouille',
    'Rauchmelder', 'Raumanzug', 'Raumschiff', 'Raumstation', 'Ravioli', 'Reagenzglas',
    'Reaktion', 'Realität', 'Realschule', 'Rechnung', 'Rechteck', 'Recycling', 'Reflexion',
    'Regenmantel', 'Regentropfen', 'Regenwald', 'Regisseur', 'Reifenpanne', 'Reinheit',
    'Reisender', 'Reisepass', 'Religion', 'Renaissance', 'Rennauto', 'Rennboot', 'Rennstrecke',
    'Rentier', 'Rentner', 'Reporter', 'Restaurant', 'Rettich', 'Rettungsring', 'Revolver',
    'Rezeption', 'Rezeptionist', 'Richter', 'Riesenrad', 'Rindfleisch', 'Ringelblume',
    'Ringfinger', 'Rockstar', 'Rollator', 'Rollenspiel', 'Rollladen', 'Rollschuhe',
    'Rollstuhl', 'Rolltreppe', 'Rosenkohl', 'Rotkehlchen', 'Rotkäppchen', 'Rucksack',
    'Rutsche', 'Röstaroma', 'Rückgrat', 'Rückspiegel', 'Rüstung', 'Sackgasse', 'Saftladen',
    'Saftpresse', 'Salzwasser', 'Samstag', 'Samurai', 'Sandalen', 'Sandbank', 'Sandburg',
    'Sandkasten', 'Sandsturm', 'Sanduhr', 'Sandwich', 'Sarkophag', 'Sauerkraut', 'Sauerstoff',
    'Saugglocke', 'Savanne', 'Saxofon', 'Scanner', 'Schacht', 'Schaffner', 'Schallplatte',
    'Schalter', 'Schamesröte', 'Schatten', 'Schatzinsel', 'Schaufel', 'Schaukel',
    'Schaumkrone', 'Schauspieler', 'Scheidung', 'Scheinwerfer', 'Scherzkeks', 'Scheune',
    'Schicksal', 'Schienbein', 'Schienen', 'Schiffstaufe', 'Schiffswrack', 'Schildkröte',
    'Schimmel', 'Schimpanse', 'Schinken', 'Schlacht', 'Schlachter', 'Schlafanzug',
    'Schlafmütze', 'Schlafsack', 'Schlagsahne', 'Schlagzeug', 'Schlange', 'Schlauch',
    'Schlauchboot', 'Schlaufe', 'Schleier', 'Schleife', 'Schleim', 'Schleuder', 'Schlitten',
    'Schlittschuh', 'Schlucht', 'Schlägel', 'Schlüssel', 'Schmerz', 'Schmied', 'Schminke',
    'Schnabel', 'Schnabeltier', 'Schnapsglas', 'Schnauze', 'Schnecke', 'Schneeball',
    'Schneebesen', 'Schneeengel', 'Schneeflocke', 'Schneefuchs', 'Schneehase', 'Schneekanone',
    'Schneekette', 'Schneekugel', 'Schneemobil', 'Schneesturm', 'Schnorchel', 'Schnuller',
    'Schnupfen', 'Schnurrbart', 'Schnurrhaare', 'Schnürsenkel', 'Schokolade', 'Scholle',
    'Schornstein', 'Schottenrock', 'Schotter', 'Schrank', 'Schranke', 'Schraube',
    'Schreibfeder', 'Schreibtisch', 'Schriftrolle', 'Schrotflinte', 'Schubkarre', 'Schublade',
    'Schuhkarton', 'Schulter', 'Schutzengel', 'Schutzhelm', 'Schwalbe', 'Schwamm', 'Schwanz',
    'Schwarm', 'Schwarz-Weiß', 'Schwein', 'Schweiß', 'Schweißer', 'Schwerkraft',
    'Schwertfisch', 'Schwimmbad', 'Schwimmer', 'Schädel', 'Schäferhund', 'Schüssel',
    'Sechseck', 'Sechserpack', 'Seegurke', 'Seehund', 'Seeigel', 'Seelöwe', 'Seepferdchen',
    'Seerose', 'Seestern', 'Seetang', 'Seewolf', 'Segelboot', 'Segelflieger', 'Sehtest',
    'Seifenblase', 'Seifenoper', 'Seilbahn', 'Seilrutsche', 'Seilspringen', 'Seiltänzer',
    'Sekunde', 'Sellerie', 'Sensenmann', 'Serviette', 'Sesamsamen', 'Shampoo', 'Sheriff',
    'Sicherung', 'Silvester', 'Sitzbank', 'Sixpack', 'Skalpell', 'Skelett', 'Skilift',
    'Skimaske', 'Skischanze', 'Skispringen', 'Skorpion', 'Skulptur', 'Skydiving', 'Skyline',
    'Smaragd', 'Smartphone', 'Snowboard', 'Sockenpuppe', 'Solarzelle', 'Sombrero', 'Songtext',
    'Sonnenbad', 'Sonnenblume', 'Sonnenbrand', 'Sonnenbrille', 'Sonnencreme', 'Sonnenschirm',
    'Sonnenstrahl', 'Sonnensystem', 'Sonntag', 'Spaghetti', 'Spaghettieis', 'Spargel',
    'Sparschwein', 'Spartacus', 'Speichel', 'Speisekammer', 'Speisekarte', 'Spender',
    'Spiegel', 'Spiegelei', 'Spieler', 'Spielplatz', 'Spielzeug', 'Spirale', 'Spitzer',
    'Spitzhacke', 'Spitzmaus', 'Splitter', 'Sprache', 'Sprechblase', 'Sprecher', 'Spritze',
    'Sprudel', 'Sprungturm', 'Sprühfarbe', 'Spüllappen', 'Spülmaschine', 'Stachelbeere',
    'Stacheldraht', 'Stadion', 'Staffelei', 'Stalagmit', 'Stalaktit', 'Stangenbrot',
    'Staubsauger', 'Staudamm', 'Steckdose', 'Stecknadel', 'Stegosaurus', 'Steigung',
    'Steinbock', 'Steinpilz', 'Steinzeit', 'Stempel', 'Stepptanz', 'Sternbild', 'Sternfrucht',
    'Sternzeichen', 'Stethoskop', 'Steuergerät', 'Steuern', 'Steuerrad', 'Stewardess',
    'Stiefel', 'Stinktier', 'Stirnband', 'Stoppschild', 'Stoppuhr', 'Stoßdämpfer',
    'Stoßstange', 'Stoßzahn', 'Strahlung', 'Strandkorb', 'Straßenbahn', 'Streamer',
    'Streichholz', 'Strickleiter', 'Strohhalm', 'Strommast', 'Stromschlag', 'Strudel',
    'Strumpf', 'Strumpfhose', 'Stubenhocker', 'Student', 'Stuhlbein', 'Stöpsel', 'Subtraktion',
    'Suchbild', 'Suchhund', 'Sumoringer', 'Superkraft', 'Supermarkt', 'Suppenkelle',
    'Surfbrett', 'Sweatshirt', 'Symphonie', 'Süßigkeiten', 'Süßkartoffel', 'Tabelle',
    'Tablett', 'Tablette', 'Tachometer', 'Tagebuch', 'Tagtraum', 'Talentshow', 'Tambourin',
    'Tankstelle', 'Tannenbaum', 'Tannenzapfen', 'Tartaros', 'Taschengeld', 'Taschenlampe',
    'Taschentuch', 'Taschenuhr', 'Taucheranzug', 'Tauchgang', 'Taufbecken', 'Tausendfüßer',
    'Tauziehen', 'Taxifahrer', 'Teddybär', 'Teebeutel', 'Teekanne', 'Teelicht', 'Teelöffel',
    'Telefon', 'Telefonbuch', 'Telefonkabel', 'Telefonzelle', 'Temperatur', 'Tentakel',
    'Terrarium', 'Terrasse', 'Teufelskreis', 'Textmarker', 'Theremin', 'Thermometer',
    'Thermoskanne', 'Thunfisch', 'Thymian', 'Tic-Tac-Toe', 'Tiefkühlfach', 'Tierarzt',
    'Tierfutter', 'Tierhandlung', 'Tierheim', 'Tintenfisch', 'Tintenklecks', 'Tiramisu',
    'Tischdecke', 'Tischplatte', 'Tischtennis', 'Toastbrot', 'Toaster', 'Tochter', 'Toilette',
    'Tonleiter', 'Topflappen', 'Topfschlagen', 'Tornado', 'Torpedo', 'Tortenheber',
    'Totenkopf', 'Tourist', 'Tragfläche', 'Trainer', 'Traktor', 'Trauben', 'Traubensaft',
    'Traumfänger', 'Treibsand', 'Treppenhaus', 'Tresorraum', 'Tretboot', 'Tretmühle',
    'Triangel', 'Triceratops', 'Trichter', 'Triebwerk', 'Trinkgeld', 'Trittstufe', 'Trommel',
    'Trompete', 'Tropfen', 'Trophäe', 'Truthahn', 'Trüffel', 'Tsunami', 'Tumbleweed',
    'Tunnelblick', 'Tupperdose', 'Turmalin', 'Türklinke', 'Türschloss', 'Türsteher',
    'Türstopper', 'Ukulele', 'Ungeheuer', 'Uniform', 'Universität', 'Universum', 'Unterarm',
    'Untergrund', 'Unterhose', 'Unterschrift', 'Untersetzer', 'Unterwäsche', 'Urknall',
    'Vanille', 'Veganer', 'Vegetarier', 'Veilchen', 'Velociraptor', 'Veranda', 'Verband',
    'Verbrecher', 'Verbrennung', 'Verkehr', 'Verlierer', 'Verlies', 'Vermieter', 'Verpackung',
    'Versicherung', 'Versteck', 'Verstärker', 'Videospiel', 'Viertel', 'Violine',
    'Visitenkarte', 'Vitamin', 'Vlogger', 'Vogelbad', 'Vogelbeere', 'Vogelhaus', 'Vogelkäfig',
    'Vogelspinne', 'Vogelstrauß', 'Volleyball', 'Vollkornbrot', 'Vollmond', 'Vorhang',
    'Vulkanologe', 'Vuvuzela', 'Wachturm', 'Waffeleisen', 'Waisenkind', 'Waldbrand', 'Walnuss',
    'Walross', 'Wanderstock', 'Wandteppich', 'Warndreieck', 'Warnweste', 'Waschbecken',
    'Waschbär', 'Waschlappen', 'Waschmittel', 'Waschstraße', 'Wasserball', 'Wasserbett',
    'Wasserfall', 'Wasserhahn', 'Wassermelone', 'Wasserpfeife', 'Wasserturm', 'Wasserwerfer',
    'Webseite', 'Weihnachten', 'Weinglas', 'Weinrebe', 'Weintrauben', 'Weitsprung',
    'Weißwurst', 'Weltraum', 'Wendekreis', 'Werbespot', 'Werbung', 'Werkstatt', 'Werwolf',
    'Wetterfrosch', 'Whiskey', 'Whiteboard', 'Widerstand', 'Wilderer', 'Wildnis',
    'Wildschwein', 'Windbeutel', 'Windhose', 'Windpark', 'Windrad', 'Windsack', 'Windsurfer',
    'Winkekatze', 'Winterschlaf', 'Wirbelsäule', 'Wissenschaft', 'Wohlstand', 'Wohnung',
    'Wohnwagen', 'Wohnzimmer', 'Wrestler', 'Wrestling', 'Wunderlampe', 'Wunderland',
    'Wunschliste', 'Wärmflasche', 'Wäscheleine', 'Wäschespinne', 'Wörterbuch', 'Würfelbecher',
    'Würfelqualle', 'Wüstenfuchs', 'Xylofon', 'Youtuber', 'Zahnarzt', 'Zahnbürste', 'Zahnfee',
    'Zahnlücke', 'Zahnpasta', 'Zahnrad', 'Zahnseide', 'Zahnspange', 'Zahnstein', 'Zahnstocher',
    'Zauberer', 'Zaubertrank', 'Zaubertrick', 'Zauberwürfel', 'Zehnagel', 'Zeigefinger',
    'Zeitbombe', 'Zeitlupe', 'Zeitmaschine', 'Zeitung', 'Zentaur', 'Zeppelin', 'Zeugnis',
    'Zickzack', 'Ziegelstein', 'Ziegenbart', 'Zielscheibe', 'Zigarette', 'Zigarre',
    'Zimmermann', 'Zimtrolle', 'Zitrone', 'Zitteraal', 'Zoowärter', 'Zucchini', 'Zuckerguss',
    'Zuckerstange', 'Zuckerwatte', 'Zugbrücke', 'Zwieback', 'Zwiebel', 'Zwillinge', 'Zylinder',
    'Zypresse', 'Zündschnur', 'Äffchen', 'Äquator', 'Überfall', 'Überlebender', 'Überraschung',
    'Überschrift',
  ]),
  ...words('schwer', [
    'Tellerrand', 'Lagspike', 'Cooldown', 'Frame-Drop', 'Serverabsturz', 'Tastenkombination',
    'Bildwiederholrate', 'Latenzzeit', 'Übertaktung', 'Wasserkühlung', 'Netzteilkabel',
    'Sanduhr-Symbol', 'Optische Täuschung', 'Perpetuum Mobile', 'Zeitzone', 'Sonnenfinsternis',
    'Nordlicht', 'Fata Morgana', 'Echo', 'Schwerelosigkeit', 'Zentrifugalkraft', 'Marionette',
    'Scherenschnitt', 'Schattentheater', 'Wasserwaage', 'Stimmgabel', 'Wetterhahn',
    'Sanduhrfigur', 'Sternschnuppe', 'Morsecode', 'Rauchzeichen', 'Flaschenpost',
    // Zusätzliche Wörter aus der skribbl.io-Wortliste (siehe Kommentar oben bei 'leicht')
    'Abschleppwagen', 'Achillessehne', 'Adventskalender', 'Alphastrahlung', 'Altglascontainer',
    'Altweibersommer', 'Ameisenhaufen', 'Ampelmännchen', 'Anhängerkupplung',
    'Anrufbeantworter', 'Arbeitszimmer', 'Archaeopteryx', 'Armaturenbrett', 'Asteroidengürtel',
    'Aussichtspunkt', 'Außerirdischer', 'Bananenplantage', 'Bananenschale', 'Baseballschläger',
    'Benachrichtigung', 'Bienenkönigin', 'Brachiosaurus', 'Bremsschwelle', 'Brillenputztuch',
    'Brillenschlange', 'Brustschwimmen', 'Bushaltestelle', 'Bürgermeister', 'Champagnersorbet',
    'Christbaumkugel', 'Deckenventilator', 'Defibrillator', 'Demonstration',
    'Desoxyribonukleinsäure', 'Doppeldeckerbus', 'Drachenfrucht', 'Eierschachtel',
    'Einbahnstraße', 'Einkaufswagen', 'Einkaufszentrum', 'Einschränkung', 'Erdnussbutter',
    'Federmäppchen', 'Fensterklappe', 'Fernbedienung', 'Feuersalamander', 'Feuerwehrauto',
    'Feuerwehrmann', 'Fingerabdruck', 'Fischstäbchen', 'Fitnesscenter', 'Flammenwerfer',
    'Flaschendrehen', 'Flaschenöffner', 'Fleischbällchen', 'Fliegenklatsche',
    'Freiheitsstatue', 'Freundschaftsband', 'Frühlingsrolle', 'Galgenmännchen',
    'Gebrauchtwagenhändler', 'Gefrierschrank', 'Geisterfahrer', 'Geisterschiff',
    'Geschenkpapier', 'Geschirrschrank', 'Geschirrspüler', 'Gesichtsbemalung',
    'Getränkeautomat', 'Gleichgewicht', 'Gottesanbeterin', 'Grafiktablett', 'Grubenarbeiter',
    'Gummiwürmchen', 'Gymnastikball', 'Gänseblümchen', 'Hamsterbacken', 'Handschuhfach',
    'Haubentaucher', 'Heiligenschein', 'Heinzelmännchen', 'Heiratsantrag', 'Heizungskessel',
    'Heißluftballon', 'Hochspannungsmast', 'Hochzeitsglocken', 'Hochzeitskutsche',
    'Hängebauchschwein', 'Höhlenforscher', 'Irokesenfrisur', 'Kaffeemaschine',
    'Kaiserschmarrn', 'Kaltwachsstreifen', 'Kanarienvogel', 'Kartoffelbrei', 'Kartoffelpuffer',
    'Kartoffelschäler', 'Kartoffelsuppe', 'Kaugummikugel', 'Kernkraftwerk',
    'Kernspintomografie', 'Kerzenleuchter', 'Kerzenständer', 'Kettenkarussell',
    'Kissenschlacht', 'Klapperschlange', 'Klassenzimmer', 'Kleiderschrank', 'Kleiderständer',
    'Kondenswasser', 'Kopfschmerzen', 'Krankenschwester', 'Kreuzworträtsel', 'Krokodilsträne',
    'Kugelschreiber', 'Kürbislaterne', 'Laktoseintoleranz', 'Lebkuchenhaus', 'Lebkuchenherz',
    'Leuchtreklame', 'Lichtschalter', 'Lockenwickler', 'Luftkissenboot', 'Lüftungsschacht',
    'Maschinengewehr', 'Meeresfrüchte', 'Meeresspiegel', 'Meerschweinchen', 'Mikrofonständer',
    'Milchschnitte', 'Mineralwasser', 'Mitfahrgelegenheit', 'Modelleisenbahn',
    'Motorradfahrer', 'Multiplikation', 'Mundharmonika', 'Nachbarschaft', 'Nachtsichtgerät',
    'Navigationssystem', 'Netzhautscanner', 'Nichtschwimmer', 'Nikolausstiefel',
    'Notenschlüssel', 'Observatorium', 'Ohrenschützer', 'Papageientaucher', 'Papierflieger',
    'Parallelogramm', 'Paralleluniversum', 'Patronenhülse', 'Personenschützer',
    'Pfannenwender', 'Pfeffersalami', 'Pferdeschwanz', 'Pflanzenfresser', 'Photosynthese',
    'Presslufthammer', 'Programmierer', 'Pterodactylus', 'Radioaktivität', 'Rasensprenger',
    'Reinkarnation', 'Reißverschluss', 'Reißverschlussverfahren', 'Rettungsweste',
    'Ringelschwanz', 'Räucherstäbchen', 'Röntgenstrahlung', 'Rückenschmerzen',
    'Satellitenschüssel', 'Sattelschlepper', 'Schaltknüppel', 'Scharfschütze',
    'Schaufensterpuppe', 'Schaukelpferd', 'Schaukelstuhl', 'Schaumschläger', 'Scheibenwischer',
    'Schiedsrichter', 'Schlafenszeit', 'Schlammschlacht', 'Schlangenbeschwörer',
    'Schleichwerbung', 'Schleifpapier', 'Schlüsselanhänger', 'Schlüsselbein', 'Schlüsselbund',
    'Schlüsselloch', 'Schmetterling', 'Schneeballschlacht', 'Schneeglöckchen', 'Schneekönigin',
    'Schneewittchen', 'Schnellstraße', 'Schornsteinfeger', 'Schraubendreher',
    'Schraubenschlüssel', 'Schreibmaschine', 'Schreibschrift', 'Schreibtischstuhl',
    'Schriftsteller', 'Schulterpolster', 'Schwarzpulver', 'Schweinestall', 'Science-Fiction',
    'Segelflugzeug', 'Sicherheitsdienst', 'Sicherheitsgurt', 'Sicherheitsnadel',
    'Silberbesteck', 'Skateboardfahrer', 'Sommersprossen', 'Sonnenaufgang', 'Spaghettimonster',
    'Stachelrochen', 'Stachelschwein', 'Stockcarrennen', 'Straßenlaterne', 'Straßensperre',
    'Streichholzschachtel', 'Strichmännchen', 'Süßigkeitenautomat', 'Tannenbaumständer',
    'Taschenmesser', 'Taschenrechner', 'Tennisschläger', 'Tintenpatrone',
    'Tischtennisschläger', 'Toilettenbürste', 'Toilettenpapier', 'Trillerpfeife',
    'Trommelwirbel', 'Tropfsteinhöhle', 'Uhrzeigersinn', 'Umweltverschmutzung',
    'Unterschenkel', 'Venusfliegenfalle', 'Verfolgungsjagd', 'Verkehrsinsel',
    'Verkehrskontrolle', 'Versicherungskaufmann', 'Veröffentlichung', 'Vorschlaghammer',
    'Vorstellungskraft', 'Vulkanausbruch', 'Warteschlange', 'Waschbrettbauch', 'Waschmaschine',
    'Wasserfarbkasten', 'Wasserkreislauf', 'Wasserpistole', 'Wasserrutsche',
    'Wasserschildkröte', 'Wattestäbchen', 'Weihnachtsbaum', 'Weihnachtsmann', 'Wellensittich',
    'Werkzeugkasten', 'Wettervorhersage', 'Wildwasserbahn', 'Windschutzscheibe',
    'Winterstiefel', 'Wissenschaftler', 'Wolkenkratzer', 'Wunschbrunnen', 'Wäscheklammer',
    'Zebrastreifen', 'Zimmerpflanze', 'Zirkusdirektor', 'Zwischendecke', 'Überschwemmung',
    'Überwachungskamera',
  ]),
];
