const NODE_VERSION = 'v22.17.1';

export function buildControllerSetup(config: {
  respawnBaseUrl: string;
  pairingCode: string;
  accessToken: string;
}) {
  return {
    respawnBaseUrl: config.respawnBaseUrl,
    pairingCode: config.pairingCode,
    accessToken: config.accessToken,
    label: 'LAN-Musikgerät',
  };
}

export function buildUnixLauncher(): string {
  return [
    '#!/usr/bin/env bash',
    'set -euo pipefail',
    'DIR="$(cd "$(dirname "$0")" && pwd)"',
    'INSTALL_DIR="$HOME/.respawn/jam-controller-app"',
    '',
    'if [ "$DIR" != "$INSTALL_DIR" ]; then',
    '  mkdir -p "$INSTALL_DIR"',
    '  cp "$DIR/jam-controller.mjs" "$DIR/controller-setup.json" "$INSTALL_DIR/"',
    '  cp "$DIR/Start-macOS.command" "$DIR/start-linux.sh" "$INSTALL_DIR/"',
    '  chmod +x "$INSTALL_DIR/Start-macOS.command" "$INSTALL_DIR/start-linux.sh"',
    '  echo "Der Jam-Controller wurde dauerhaft unter $INSTALL_DIR installiert."',
    '  exec "$INSTALL_DIR/$(basename "$0")"',
    'fi',
    '',
    `VERSION="${NODE_VERSION}"`,
    'RUNTIME="$DIR/.runtime"',
    'NODE="$RUNTIME/bin/node"',
    '',
    'if [ ! -x "$NODE" ]; then',
    '  OS_RAW="$(uname -s)"',
    '  ARCH_RAW="$(uname -m)"',
    '  case "$OS_RAW" in Darwin) OS="darwin" ;; Linux) OS="linux" ;; *) echo "Nicht unterstütztes System: $OS_RAW"; exit 1 ;; esac',
    '  case "$ARCH_RAW" in arm64|aarch64) ARCH="arm64" ;; x86_64|amd64) ARCH="x64" ;; armv7l) ARCH="armv7l" ;; *) echo "Nicht unterstützte Architektur: $ARCH_RAW"; exit 1 ;; esac',
    '  NAME="node-$VERSION-$OS-$ARCH"',
    '  ARCHIVE="$NAME.tar.gz"',
    '  BASE="https://nodejs.org/dist/$VERSION"',
    '  TMP="$DIR/.runtime-download"',
    '  rm -rf "$TMP" "$RUNTIME"',
    '  mkdir -p "$TMP"',
    '  echo "Die private Controller-Laufzeit wird einmalig geladen…"',
    '  curl -fL "$BASE/$ARCHIVE" -o "$TMP/$ARCHIVE"',
    '  EXPECTED="$(curl -fsSL "$BASE/SHASUMS256.txt" | awk -v file="$ARCHIVE" \'$2 == file { print $1 }\')"',
    '  if command -v shasum >/dev/null 2>&1; then ACTUAL="$(shasum -a 256 "$TMP/$ARCHIVE" | awk \'{print $1}\')"; else ACTUAL="$(sha256sum "$TMP/$ARCHIVE" | awk \'{print $1}\')"; fi',
    '  if [ -z "$EXPECTED" ] || [ "$EXPECTED" != "$ACTUAL" ]; then echo "Prüfsumme der Laufzeit stimmt nicht."; exit 1; fi',
    '  tar -xzf "$TMP/$ARCHIVE" -C "$TMP"',
    '  mv "$TMP/$NAME" "$RUNTIME"',
    '  rm -rf "$TMP"',
    'fi',
    '',
    'exec "$NODE" "$DIR/jam-controller.mjs"',
    '',
  ].join('\n');
}

export function buildWindowsLauncher(): string {
  return [
    '@echo off',
    'setlocal',
    'set "DIR=%~dp0"',
    'powershell -NoProfile -ExecutionPolicy Bypass -File "%DIR%start-windows.ps1"',
    'if errorlevel 1 pause',
    '',
  ].join('\r\n');
}

export function buildWindowsPowerShell(): string {
  return [
    "$ErrorActionPreference = 'Stop'",
    '$Dir = Split-Path -Parent $MyInvocation.MyCommand.Path',
    '$InstallDir = Join-Path $HOME ".respawn\\jam-controller-app"',
    'if (-not [string]::Equals($Dir.TrimEnd("\\"), $InstallDir.TrimEnd("\\"), [System.StringComparison]::OrdinalIgnoreCase)) {',
    '  New-Item $InstallDir -ItemType Directory -Force | Out-Null',
    '  Copy-Item (Join-Path $Dir "jam-controller.mjs"), (Join-Path $Dir "controller-setup.json"), (Join-Path $Dir "Start-Windows.cmd"), (Join-Path $Dir "start-windows.ps1") -Destination $InstallDir -Force',
    '  Write-Host "Der Jam-Controller wurde dauerhaft unter $InstallDir installiert."',
    '  & (Join-Path $InstallDir "start-windows.ps1")',
    '  exit $LASTEXITCODE',
    '}',
    `$Version = '${NODE_VERSION}'`,
    "$Arch = if ($env:PROCESSOR_ARCHITECTURE -eq 'ARM64') { 'arm64' } else { 'x64' }",
    '$Name = "node-$Version-win-$Arch"',
    '$Runtime = Join-Path $Dir ".runtime"',
    '$Node = Join-Path $Runtime "node.exe"',
    'if (-not (Test-Path $Node)) {',
    '  $Base = "https://nodejs.org/dist/$Version"',
    '  $Archive = "$Name.zip"',
    '  $Temp = Join-Path $Dir ".runtime-download"',
    '  Remove-Item $Temp, $Runtime -Recurse -Force -ErrorAction SilentlyContinue',
    '  New-Item $Temp -ItemType Directory | Out-Null',
    '  Write-Host "Die private Controller-Laufzeit wird einmalig geladen..."',
    '  $Zip = Join-Path $Temp $Archive',
    '  Invoke-WebRequest "$Base/$Archive" -OutFile $Zip',
    '  $Sums = (Invoke-WebRequest "$Base/SHASUMS256.txt").Content -split "`n"',
    '  $Line = $Sums | Where-Object { $_ -match "\\s$([regex]::Escape($Archive))$" } | Select-Object -First 1',
    '  $Expected = ($Line -split "\\s+")[0].ToLowerInvariant()',
    '  $Actual = (Get-FileHash $Zip -Algorithm SHA256).Hash.ToLowerInvariant()',
    '  if (-not $Expected -or $Expected -ne $Actual) { throw "Pruefsumme der Laufzeit stimmt nicht." }',
    '  Expand-Archive $Zip -DestinationPath $Temp',
    '  Move-Item (Join-Path $Temp $Name) $Runtime',
    '  Remove-Item $Temp -Recurse -Force',
    '}',
    '& $Node (Join-Path $Dir "jam-controller.mjs")',
    '',
  ].join('\r\n');
}

export function buildControllerReadme(): string {
  return [
    'RESPAWN JAM-CONTROLLER',
    '',
    'WOFÜR IST DER CONTROLLER DA?',
    '',
    'Dieser eine Musik-PC oder Raspberry Pi verbindet Respawn mit Spotify.',
    'Alle Teilnehmenden bedienen Titel, Playlists, Songwünsche und Wiedergabe im Respawn-Browser.',
    'Sie benötigen weder ein eigenes Spotify-Konto noch dieses Paket.',
    'Eine gestartete Playlist ersetzt die bisherige Warteschlange. Respawn zeigt die noch folgenden',
    'Playlist-Titel und führt zusätzliche Songwünsche getrennt in Eingangsreihenfolge auf.',
    '',
    'ERSTE INSTALLATION',
    '',
    '1. ZIP vollständig entpacken.',
    '2. macOS: "Start-macOS.command" doppelklicken.',
    '   Windows: "Start-Windows.cmd" doppelklicken.',
    '   Raspberry Pi/Linux: im entpackten Ordner "bash start-linux.sh" ausführen.',
    '3. Der Controller installiert sich dauerhaft unter ~/.respawn/jam-controller-app.',
    '4. Beim ersten Start wird dort automatisch eine geprüfte private Node.js-Laufzeit geladen.',
    '5. Die lokale Einrichtung öffnet sich automatisch. Spotify Client-ID eintragen, die angezeigte',
    '   Redirect URI im Spotify Developer Dashboard hinterlegen und mit Spotify anmelden.',
    '6. Optional auf http://127.0.0.1:43821 den Autostart aktivieren.',
    '',
    'Respawn-Adresse und Kopplungscode sind im Paket bereits eingetragen.',
    'Repository, npm und eine vorhandene Node.js-Installation sind nicht nötig. Nach erfolgreicher',
    'Installation kann dieser entpackte Downloadordner gelöscht werden.',
    '',
    'SPÄTER STARTEN UND WIEDERVERBINDEN',
    '',
    'Für den normalen Start dieselbe Startdatei verwenden; sie öffnet die installierte Version.',
    'Das ZIP wird nicht erneut benötigt. Mit aktiviertem Autostart startet der Controller selbst.',
    'Solange er läuft, versucht er unterbrochene Respawn- und Spotify-Verbindungen automatisch erneut.',
    'Ein kurzer Ausfall braucht weder Skript-Neustart noch neuen Kopplungscode.',
    '',
    'Verlangt Respawn eine neue Kopplung, in Mehr -> Jam einen neuen Code erzeugen und auf',
    'http://127.0.0.1:43821 unter "Wieder verbinden" eingeben. Die Spotify-Anmeldung bleibt erhalten.',
    'Ist nur Spotify abgemeldet, dort "Spotify-Anmeldung erneuern" wählen. Kein neuer Download nötig.',
    'Einen neuen Download braucht es nur, wenn die Installation fehlt oder das Musikgerät ersetzt wird.',
    '',
    'DATENSCHUTZ',
    '',
    'Spotify Client-ID und OAuth-Tokens bleiben lokal unter ~/.respawn/jam-controller.json.',
    'Respawn erhält nur öffentliche Wiedergabedaten und einen gehashten Controller-Schlüssel.',
    'Das Musikgerät ist kein Spieler und erscheint nicht in Spielerlisten oder Statistiken.',
    '',
  ].join('\n');
}
